/**
 * Static airline profiles for the /airlines hub pages.
 *
 * Each entry's `name` must match the operator strings in SEED_META
 * character-for-character — that is what links fiches to their airline
 * page. All facts below were verified against public sources (IATA/ICAO
 * listings, airline websites, Wikipedia) on 2026-09-23. No API, no quota:
 * this is a static table baked at build time.
 */
export type Alliance = "Star Alliance" | "SkyTeam" | "oneworld";

export interface AirlineInfo {
  /** Exact operator name as it appears in SEED_META. */
  name: string;
  /** URL slug under /airlines/. */
  slug: string;
  /**
   * Airline codes. Omitted for non-airline operators (manufacturers flying
   * their own testbeds) — the page then skips those fact rows.
   */
  iata?: string;
  icao?: string;
  callsign?: string;
  /** i18n key for the country name (country* keys in lib/i18n.ts). */
  countryKey: MessageKey;
  founded: number;
  alliance: Alliance | null;
  /** e.g. ["Paris (CDG)", "Amsterdam (AMS)"] */
  hubs: string[];
  /**
   * Bare domain, e.g. "airfrance.com". Omitted for defunct airlines
   * (no official site anymore) — pages then skip the website row.
   */
  website?: string;
  /**
   * When true, no logo file is shipped for this airline (e.g. licensing)
   * and UIs must render the ✈ glyph fallback instead of the SVG.
   */
  noLogo?: boolean;
}

export const AIRLINES: AirlineInfo[] = [
  {
    name: "Emirates Airline",
    slug: "emirates-airline",
    iata: "EK",
    icao: "UAE",
    callsign: "EMIRATES",
    countryKey: "countryUAE",
    founded: 1985,
    alliance: null,
    hubs: ["Dubai (DXB)"],
    website: "emirates.com",
  },
  {
    name: "Air France",
    slug: "air-france",
    iata: "AF",
    icao: "AFR",
    callsign: "AIRFRANS",
    countryKey: "countryFrance",
    founded: 1933,
    alliance: "SkyTeam",
    hubs: ["Paris (CDG)", "Paris (ORY)"],
    website: "airfrance.com",
  },
  {
    name: "Turkish Airlines",
    slug: "turkish-airlines",
    iata: "TK",
    icao: "THY",
    callsign: "TURKISH",
    countryKey: "countryTurkey",
    founded: 1933,
    alliance: "Star Alliance",
    hubs: ["Istanbul (IST)"],
    website: "turkishairlines.com",
  },
  {
    name: "Qatar Airways",
    slug: "qatar-airways",
    iata: "QR",
    icao: "QTR",
    callsign: "QATARI",
    countryKey: "countryQatar",
    founded: 1993,
    alliance: "oneworld",
    hubs: ["Doha (DOH)"],
    website: "qatarairways.com",
  },
  {
    name: "Qantas",
    slug: "qantas",
    iata: "QF",
    icao: "QFA",
    callsign: "QANTAS",
    countryKey: "countryAustralia",
    founded: 1920,
    alliance: "oneworld",
    hubs: ["Sydney (SYD)", "Melbourne (MEL)", "Brisbane (BNE)"],
    website: "qantas.com",
  },
  {
    name: "KLM Royal Dutch Airlines",
    slug: "klm-royal-dutch-airlines",
    iata: "KL",
    icao: "KLM",
    callsign: "KLM",
    countryKey: "countryNetherlands",
    founded: 1919,
    alliance: "SkyTeam",
    hubs: ["Amsterdam (AMS)"],
    website: "klm.com",
  },
  {
    name: "Delta Air Lines",
    slug: "delta-air-lines",
    iata: "DL",
    icao: "DAL",
    callsign: "DELTA",
    countryKey: "countryUSA",
    founded: 1924,
    alliance: "SkyTeam",
    hubs: ["Atlanta (ATL)", "Detroit (DTW)", "Minneapolis (MSP)"],
    website: "delta.com",
  },
  {
    name: "Thai Airways International",
    slug: "thai-airways-international",
    iata: "TG",
    icao: "THA",
    callsign: "THAI",
    countryKey: "countryThailand",
    founded: 1960,
    alliance: "Star Alliance",
    hubs: ["Bangkok (BKK)", "Phuket (HKT)"],
    website: "thaiairways.com",
  },
  {
    name: "Swiss International Air Lines",
    slug: "swiss-international-air-lines",
    iata: "LX",
    icao: "SWR",
    callsign: "SWISS",
    countryKey: "countrySwitzerland",
    founded: 2002,
    alliance: "Star Alliance",
    hubs: ["Zurich (ZRH)", "Geneva (GVA)"],
    website: "swiss.com",
  },
  {
    name: "Singapore Airlines",
    slug: "singapore-airlines",
    iata: "SQ",
    icao: "SIA",
    callsign: "SINGAPORE",
    countryKey: "countrySingapore",
    founded: 1947,
    alliance: "Star Alliance",
    hubs: ["Singapore (SIN)"],
    website: "singaporeair.com",
  },
  {
    name: "Malaysia Airlines",
    slug: "malaysia-airlines",
    iata: "MH",
    icao: "MAS",
    callsign: "MALAYSIAN",
    countryKey: "countryMalaysia",
    founded: 1947,
    alliance: "oneworld",
    hubs: ["Kuala Lumpur (KUL)", "Kota Kinabalu (BKI)"],
    website: "malaysiaairlines.com",
  },
  {
    name: "Lufthansa",
    slug: "lufthansa",
    iata: "LH",
    icao: "DLH",
    callsign: "LUFTHANSA",
    countryKey: "countryGermany",
    founded: 1953,
    alliance: "Star Alliance",
    hubs: ["Frankfurt (FRA)", "Munich (MUC)"],
    website: "lufthansa.com",
  },
  {
    name: "LOT Polish Airlines",
    slug: "lot-polish-airlines",
    iata: "LO",
    icao: "LOT",
    callsign: "LOT",
    countryKey: "countryPoland",
    founded: 1928,
    alliance: "Star Alliance",
    hubs: ["Warsaw (WAW)", "Kraków (KRK)"],
    website: "lot.com",
  },
  {
    name: "Gulf Air",
    slug: "gulf-air",
    iata: "GF",
    icao: "GFA",
    callsign: "GULF AIR",
    countryKey: "countryBahrain",
    founded: 1950,
    alliance: null,
    hubs: ["Bahrain (BAH)"],
    website: "gulfair.com",
  },
  {
    name: "Finnair",
    slug: "finnair",
    iata: "AY",
    icao: "FIN",
    callsign: "FINNAIR",
    countryKey: "countryFinland",
    founded: 1923,
    alliance: "oneworld",
    hubs: ["Helsinki (HEL)"],
    website: "finnair.com",
  },
  {
    name: "Etihad Airways",
    slug: "etihad-airways",
    iata: "EY",
    icao: "ETD",
    callsign: "ETIHAD",
    countryKey: "countryUAE",
    founded: 2003,
    alliance: null,
    hubs: ["Abu Dhabi (AUH)"],
    website: "etihad.com",
  },
  {
    name: "EL AL",
    slug: "el-al",
    iata: "LY",
    icao: "ELY",
    callsign: "ELAL",
    countryKey: "countryIsrael",
    founded: 1948,
    alliance: null,
    hubs: ["Tel Aviv (TLV)"],
    website: "elal.com",
  },
  {
    name: "Cathay Pacific Airways",
    slug: "cathay-pacific-airways",
    iata: "CX",
    icao: "CPA",
    callsign: "CATHAY",
    countryKey: "countryHongKong",
    founded: 1946,
    alliance: "oneworld",
    hubs: ["Hong Kong (HKG)"],
    website: "cathaypacific.com",
  },
  {
    name: "British Airways",
    slug: "british-airways",
    iata: "BA",
    icao: "BAW",
    callsign: "SPEEDBIRD",
    countryKey: "countryUK",
    founded: 1974,
    alliance: "oneworld",
    hubs: ["London (LHR)", "London (LGW)"],
    website: "britishairways.com",
  },
  {
    name: "Austrian Airlines",
    slug: "austrian-airlines",
    iata: "OS",
    icao: "AUA",
    callsign: "AUSTRIAN",
    countryKey: "countryAustria",
    founded: 1957,
    alliance: "Star Alliance",
    hubs: ["Vienna (VIE)"],
    website: "austrian.com",
  },
  {
    name: "All Nippon Airways",
    slug: "all-nippon-airways",
    iata: "NH",
    icao: "ANA",
    callsign: "ALL NIPPON",
    countryKey: "countryJapan",
    founded: 1952,
    alliance: "Star Alliance",
    hubs: ["Tokyo (HND)", "Tokyo (NRT)", "Osaka (KIX)"],
    website: "ana.co.jp",
  },
  {
    name: "Air New Zealand",
    slug: "air-new-zealand",
    iata: "NZ",
    icao: "ANZ",
    callsign: "NEW ZEALAND",
    countryKey: "countryNewZealand",
    founded: 1940,
    alliance: "Star Alliance",
    hubs: ["Auckland (AKL)", "Christchurch (CHC)", "Wellington (WLG)"],
    website: "airnewzealand.com",
  },
  {
    name: "Air India",
    slug: "air-india",
    iata: "AI",
    icao: "AIC",
    callsign: "AIRINDIA",
    countryKey: "countryIndia",
    founded: 1932,
    alliance: "Star Alliance",
    hubs: ["Delhi (DEL)", "Mumbai (BOM)", "Bengaluru (BLR)"],
    website: "airindia.com",
  },
  {
    name: "Air Canada",
    slug: "air-canada",
    iata: "AC",
    icao: "ACA",
    callsign: "AIR CANADA",
    countryKey: "countryCanada",
    founded: 1937,
    alliance: "Star Alliance",
    hubs: ["Toronto (YYZ)", "Montreal (YUL)", "Vancouver (YVR)"],
    website: "aircanada.com",
  },
  {
    name: "AeroMexico",
    slug: "aeromexico",
    iata: "AM",
    icao: "AMX",
    callsign: "AEROMEXICO",
    countryKey: "countryMexico",
    founded: 1934,
    alliance: "SkyTeam",
    hubs: ["Mexico City (MEX)", "Guadalajara (GDL)", "Monterrey (MTY)"],
    website: "aeromexico.com",
  },
  {
    name: "Korean Air",
    slug: "korean-air",
    iata: "KE",
    icao: "KAL",
    callsign: "KOREAN AIR",
    countryKey: "countrySouthKorea",
    founded: 1962,
    alliance: "SkyTeam",
    hubs: ["Seoul (ICN)", "Seoul (GMP)"],
    website: "koreanair.com",
  },
  {
    name: "Ethiopian Cargo",
    slug: "ethiopian-cargo",
    iata: "ET",
    icao: "ETH",
    callsign: "ETHIOPIAN",
    countryKey: "countryEthiopia",
    founded: 1945,
    alliance: "Star Alliance",
    hubs: ["Addis Ababa (ADD)", "Liège (LGG)"],
    website: "ethiopianairlines.com",
  },
  {
    name: "Ethiopian Airlines",
    slug: "ethiopian-airlines",
    iata: "ET",
    icao: "ETH",
    callsign: "ETHIOPIAN",
    countryKey: "countryEthiopia",
    founded: 1945,
    alliance: "Star Alliance",
    hubs: ["Addis Ababa (ADD)", "Lomé (LFW)", "Lusaka (LUN)"],
    website: "ethiopianairlines.com",
  },
  {
    name: "Northwest Airlines",
    slug: "northwest-airlines",
    iata: "NW",
    icao: "NWA",
    callsign: "NORTHWEST",
    countryKey: "countryUSA",
    founded: 1926,
    alliance: null,
    hubs: ["Minneapolis (MSP)", "Detroit (DTW)", "Tokyo (NRT)"],
  },
  {
    name: "Scandinavian Airlines",
    slug: "scandinavian-airlines",
    iata: "SK",
    icao: "SAS",
    callsign: "SCANDINAVIAN",
    countryKey: "countryScandinavia",
    founded: 1946,
    alliance: "SkyTeam",
    hubs: ["Copenhagen (CPH)", "Oslo (OSL)", "Stockholm (ARN)"],
    website: "flysas.com",
  },
  {
    name: "Asiana Airlines",
    slug: "asiana-airlines",
    iata: "OZ",
    icao: "AAR",
    callsign: "ASIANA",
    countryKey: "countrySouthKorea",
    founded: 1988,
    alliance: "Star Alliance",
    hubs: ["Seoul (ICN)"],
    website: "flyasiana.com",
  },
  {
    name: "United Airlines",
    slug: "united-airlines",
    iata: "UA",
    icao: "UAL",
    callsign: "UNITED",
    countryKey: "countryUSA",
    founded: 1926,
    alliance: "Star Alliance",
    hubs: ["Chicago (ORD)", "Denver (DEN)"],
    website: "united.com",
  },
  {
    name: "American Airlines",
    slug: "american-airlines",
    iata: "AA",
    icao: "AAL",
    callsign: "AMERICAN",
    countryKey: "countryUSA",
    founded: 1926,
    alliance: "oneworld",
    hubs: ["Dallas/Fort Worth (DFW)", "Charlotte (CLT)"],
    website: "aa.com",
  },
  {
    name: "Japan Airlines",
    slug: "japan-airlines",
    iata: "JL",
    icao: "JAL",
    callsign: "JAPAN AIR",
    countryKey: "countryJapan",
    founded: 1951,
    alliance: "oneworld",
    hubs: ["Tokyo (HND)", "Tokyo (NRT)"],
    website: "jal.co.jp",
  },
  {
    name: "Southwest Airlines",
    slug: "southwest-airlines",
    iata: "WN",
    icao: "SWA",
    callsign: "SOUTHWEST",
    countryKey: "countryUSA",
    founded: 1967,
    alliance: null,
    hubs: ["Dallas (DAL)", "Denver (DEN)"],
    website: "southwest.com",
  },
  {
    name: "Alaska Airlines",
    slug: "alaska-airlines",
    iata: "AS",
    icao: "ASA",
    callsign: "ALASKA",
    countryKey: "countryUSA",
    founded: 1932,
    alliance: "oneworld",
    hubs: ["Seattle (SEA)"],
    website: "alaskaair.com",
  },
  {
    name: "Ryanair",
    slug: "ryanair",
    iata: "FR",
    icao: "RYR",
    callsign: "RYANAIR",
    countryKey: "countryIreland",
    founded: 1984,
    alliance: null,
    hubs: ["Dublin (DUB)", "London (STN)"],
    website: "ryanair.com",
  },
  {
    name: "WestJet",
    slug: "westjet",
    iata: "WS",
    icao: "WJA",
    callsign: "WESTJET",
    countryKey: "countryCanada",
    founded: 1994,
    alliance: null,
    hubs: ["Calgary (YYC)"],
    website: "westjet.com",
  },
  {
    name: "Jet2",
    slug: "jet2",
    iata: "LS",
    icao: "EXS",
    callsign: "CHANNEX",
    countryKey: "countryUK",
    founded: 2002,
    alliance: null,
    hubs: ["Leeds Bradford (LBA)", "Manchester (MAN)"],
    website: "jet2.com",
  },
  {
    name: "TUIfly",
    slug: "tuifly",
    iata: "X3",
    icao: "TUI",
    callsign: "TUI JET",
    countryKey: "countryGermany",
    founded: 1972,
    alliance: null,
    hubs: ["Hanover (HAJ)"],
    website: "tui.com",
  },
  {
    name: "Virgin Atlantic",
    slug: "virgin-atlantic",
    iata: "VS",
    icao: "VIR",
    callsign: "VIRGIN",
    countryKey: "countryUK",
    founded: 1984,
    alliance: "SkyTeam",
    hubs: ["London (LHR)"],
    website: "virginatlantic.com",
  },
  {
    name: "Norwegian Air Shuttle",
    slug: "norwegian-air-shuttle",
    iata: "DY",
    icao: "NAX",
    callsign: "NOR SHUTTLE",
    countryKey: "countryNorway",
    founded: 1993,
    alliance: null,
    hubs: ["Oslo (OSL)"],
    website: "norwegian.com",
  },
  {
    name: "Sun Country Airlines",
    slug: "sun-country-airlines",
    iata: "SY",
    icao: "SCX",
    callsign: "SUN COUNTRY",
    countryKey: "countryUSA",
    founded: 1982,
    alliance: null,
    hubs: ["Minneapolis (MSP)"],
    website: "suncountry.com",
  },
  {
    name: "Iberia",
    slug: "iberia",
    iata: "IB",
    icao: "IBE",
    callsign: "IBERIA",
    countryKey: "countrySpain",
    founded: 1927,
    alliance: "oneworld",
    hubs: ["Madrid (MAD)"],
    website: "iberia.com",
  },
  {
    name: "China Airlines",
    slug: "china-airlines",
    iata: "CI",
    icao: "CAL",
    callsign: "DYNASTY",
    countryKey: "countryTaiwan",
    founded: 1959,
    alliance: "SkyTeam",
    hubs: ["Taipei (TPE)"],
    website: "china-airlines.com",
  },
  {
    name: "China Southern Airlines",
    slug: "china-southern-airlines",
    iata: "CZ",
    icao: "CSN",
    callsign: "CHINA SOUTHERN",
    countryKey: "countryChina",
    founded: 1988,
    alliance: null,
    hubs: ["Guangzhou (CAN)"],
    website: "csair.com",
  },
  {
    name: "Air China",
    slug: "air-china",
    iata: "CA",
    icao: "CCA",
    callsign: "AIR CHINA",
    countryKey: "countryChina",
    founded: 1988,
    alliance: "Star Alliance",
    hubs: ["Beijing (PEK)"],
    website: "airchina.com",
  },
  {
    name: "LATAM Airlines",
    slug: "latam-airlines",
    iata: "LA",
    icao: "LAN",
    callsign: "LAN CHILE",
    countryKey: "countryChile",
    founded: 2012,
    alliance: null,
    hubs: ["Santiago (SCL)", "S\u00e3o Paulo (GRU)"],
    website: "latam.com",
  },
  {
    name: "Hawaiian Airlines",
    slug: "hawaiian-airlines",
    iata: "HA",
    icao: "HAL",
    callsign: "HAWAIIAN",
    countryKey: "countryUSA",
    founded: 1929,
    alliance: "oneworld",
    hubs: ["Honolulu (HNL)"],
    website: "hawaiianairlines.com",
  },
  {
    name: "UPS",
    slug: "ups",
    iata: "5X",
    icao: "UPS",
    callsign: "UPS",
    countryKey: "countryUSA",
    founded: 1988,
    alliance: null,
    hubs: ["Louisville (SDF)"],
    website: "ups.com",
  },
  {
    name: "FedEx Express",
    slug: "fedex-express",
    iata: "FX",
    icao: "FDX",
    callsign: "FEDEX",
    countryKey: "countryUSA",
    founded: 1971,
    alliance: null,
    hubs: ["Memphis (MEM)"],
    website: "fedex.com",
  },
  {
    name: "SkyLease Cargo",
    slug: "skylease-cargo",
    iata: "GG",
    icao: "KYE",
    callsign: "SKY CUBE",
    countryKey: "countryUSA",
    founded: 1969,
    alliance: null,
    hubs: ["Miami (MIA)"],
    website: "skyleasecargo.com",
    noLogo: true,
  },
  {
    name: "TWA",
    slug: "twa",
    iata: "TW",
    icao: "TWA",
    callsign: "TWA",
    countryKey: "countryUSA",
    founded: 1930,
    alliance: null,
    hubs: ["St. Louis (STL)"],
  },
  {
    name: "US Airways",
    slug: "us-airways",
    iata: "US",
    icao: "AWE",
    callsign: "CACTUS",
    countryKey: "countryUSA",
    founded: 1939,
    alliance: null,
    hubs: ["Charlotte (CLT)", "Philadelphia (PHL)"],
  },
  {
    name: "Air Japan",
    slug: "air-japan",
    iata: "NQ",
    icao: "AJX",
    callsign: "AIR JAPAN",
    countryKey: "countryJapan",
    founded: 1990,
    alliance: null,
    hubs: ["Tokyo (NRT)"],
    website: "air-japan.co.jp",
  },
  {
    name: "Eastern Airlines",
    slug: "eastern-airlines",
    iata: "2D",
    icao: "EAL",
    callsign: "EASTERN",
    countryKey: "countryUSA",
    founded: 2018,
    alliance: null,
    hubs: ["Kansas City (MCI)"],
    website: "goeasternair.com",
  },
  {
    name: "South African Airways",
    slug: "south-african-airways",
    iata: "SA",
    icao: "SAA",
    callsign: "SPRINGBOK",
    countryKey: "countrySouthAfrica",
    founded: 1934,
    alliance: "Star Alliance",
    hubs: ["Johannesburg (JNB)"],
    website: "flysaa.com",
  },
  {
    name: "Boeing",
    slug: "boeing",
    countryKey: "countryUSA",
    founded: 1916,
    alliance: null,
    hubs: ["Everett (PAE)"],
    website: "boeing.com",
  },
  {
    name: "General Electric",
    slug: "general-electric",
    countryKey: "countryUSA",
    founded: 1892,
    alliance: null,
    hubs: ["Victorville (VCV)"],
    website: "ge.com",
  },
  {
    name: "Gridiron Air",
    slug: "gridiron-air",
    iata: "GI",
    icao: "RZN",
    callsign: "RED ZONE",
    countryKey: "countryUSA",
    founded: 2021,
    alliance: null,
    hubs: ["Fort Worth (AFW)"],
    noLogo: true,
  },
  {
    name: "JetBlue",
    slug: "jetblue",
    iata: "B6",
    icao: "JBU",
    callsign: "JETBLUE",
    countryKey: "countryUSA",
    founded: 1998,
    alliance: null,
    hubs: ["New York (JFK)"],
    website: "jetblue.com",
  },
  {
    name: "easyJet",
    slug: "easyjet",
    iata: "U2",
    icao: "EZY",
    callsign: "EASY",
    countryKey: "countryUK",
    founded: 1995,
    alliance: null,
    hubs: ["London (LTN)"],
    website: "easyjet.com",
  },
  {
    name: "Icelandair",
    slug: "icelandair",
    iata: "FI",
    icao: "ICE",
    callsign: "ICEAIR",
    countryKey: "countryIceland",
    founded: 1937,
    alliance: null,
    hubs: ["Reykjavik (KEF)"],
    website: "icelandair.com",
  },
  {
    name: "TAP Air Portugal",
    slug: "tap-air-portugal",
    iata: "TP",
    icao: "TAP",
    callsign: "AIR PORTUGAL",
    countryKey: "countryPortugal",
    founded: 1945,
    alliance: "Star Alliance",
    hubs: ["Lisbon (LIS)"],
    website: "flytap.com",
  },
  {
    name: "Aer Lingus",
    slug: "aer-lingus",
    iata: "EI",
    icao: "EIN",
    callsign: "SHAMROCK",
    countryKey: "countryIreland",
    founded: 1936,
    alliance: null,
    hubs: ["Dublin (DUB)"],
    website: "aerlingus.com",
  },
  {
    name: "Vueling",
    slug: "vueling",
    iata: "VY",
    icao: "VLG",
    callsign: "VUELING",
    countryKey: "countrySpain",
    founded: 2004,
    alliance: null,
    hubs: ["Barcelona (BCN)"],
    website: "vueling.com",
  },
  {
    name: "Wizz Air",
    slug: "wizz-air",
    iata: "W6",
    icao: "WZZ",
    callsign: "WIZZ AIR",
    countryKey: "countryHungary",
    founded: 2003,
    alliance: null,
    hubs: ["Budapest (BUD)"],
    website: "wizzair.com",
  },
  {
    name: "ITA Airways",
    slug: "ita-airways",
    iata: "AZ",
    icao: "ITY",
    callsign: "ITARROW",
    countryKey: "countryItaly",
    founded: 2020,
    alliance: "Star Alliance",
    hubs: ["Rome (FCO)"],
    website: "ita-airways.com",
  },
  {
    name: "TUI Airways",
    slug: "tui-airways",
    iata: "BY",
    icao: "TOM",
    callsign: "TOMJET",
    countryKey: "countryUK",
    founded: 1962,
    alliance: null,
    hubs: ["London (LGW)"],
    website: "tui.co.uk",
  },
  {
    name: "Avianca",
    slug: "avianca",
    iata: "AV",
    icao: "AVA",
    callsign: "AVIANCA",
    countryKey: "countryColombia",
    founded: 1919,
    alliance: "Star Alliance",
    hubs: ["Bogota (BOG)"],
    website: "avianca.com",
  },
  {
    name: "Volaris",
    slug: "volaris",
    iata: "Y4",
    icao: "VOI",
    callsign: "VOLARIS",
    countryKey: "countryMexico",
    founded: 2005,
    alliance: null,
    hubs: ["Mexico City (MEX)"],
    website: "volaris.com",
  },
  {
    name: "Edelweiss Air",
    slug: "edelweiss-air",
    iata: "WK",
    icao: "EDW",
    callsign: "EDELWEISS",
    countryKey: "countrySwitzerland",
    founded: 1995,
    alliance: null,
    hubs: ["Zurich (ZRH)"],
    website: "flyedelweiss.com",
  },
  {
    name: "Discover Airlines",
    slug: "discover-airlines",
    iata: "4Y",
    icao: "OCN",
    callsign: "OCEAN",
    countryKey: "countryGermany",
    founded: 2021,
    alliance: null,
    hubs: ["Frankfurt (FRA)", "Munich (MUC)"],
    website: "discover-airlines.com",
  },
  {
    name: "Level",
    slug: "level",
    iata: "LL",
    icao: "LVL",
    callsign: "DALI",
    countryKey: "countrySpain",
    founded: 2017,
    alliance: null,
    hubs: ["Barcelona (BCN)"],
    website: "flylevel.com",
  },
  {
    name: "T'way Air",
    slug: "t-way-air",
    iata: "TW",
    icao: "TWB",
    callsign: "TEEWAY",
    countryKey: "countrySouthKorea",
    founded: 2010,
    alliance: null,
    hubs: ["Seoul (GMP)", "Seoul (ICN)"],
    website: "twayair.com",
  },
  {
    name: "Sunclass Airlines",
    slug: "sunclass-airlines",
    iata: "DK",
    icao: "VKG",
    callsign: "VIKING",
    countryKey: "countryDenmark",
    founded: 1994,
    alliance: null,
    hubs: ["Copenhagen (CPH)"],
    website: "sunclassairlines.dk",
  },
  {
    name: "Qatar Amiri Flight",
    slug: "qatar-amiri-flight",
    icao: "QAF",
    callsign: "AMIRI",
    countryKey: "countryQatar",
    founded: 1977,
    alliance: null,
    hubs: ["Doha (DOH)"],
    website: "amiriflight.gov.qa",
    noLogo: true,
  },
  {
    name: "Top Aces Inc",
    slug: "top-aces-inc",
    countryKey: "countryCanada",
    founded: 2000,
    alliance: null,
    hubs: ["Montreal (YUL)"],
    website: "topaces.com",
    noLogo: true,
  },
];

const bySlug = new Map<string, AirlineInfo>();
const byName = new Map<string, AirlineInfo>();
for (const airline of AIRLINES) {
  bySlug.set(airline.slug, airline);
  byName.set(airline.name, airline);
}

export function airlineBySlug(slug: string): AirlineInfo | undefined {
  return bySlug.get(slug);
}

export function airlineByName(name: string): AirlineInfo | undefined {
  return byName.get(name) ?? byName.get(AIRLINE_ALIASES[name] ?? "");
}

/**
 * Live lookups often return a subsidiary or long-form operator name
 * ("JetBlue Airways", "Delta Connection"). Map those to the catalog entry
 * so fiches link to the right airline page.
 */
const AIRLINE_ALIASES: Record<string, string> = {
  "JetBlue Airways": "JetBlue",
  "Vueling Airlines": "Vueling",
  "Virgin Atlantic Airways": "Virgin Atlantic",
  "United Parcel Service": "UPS",
  "Italia Trasporto Aereo": "ITA Airways",
  "T way Air": "T'way Air",
  "Avianca Costa Rica": "Avianca",
  "Delta Connection": "Delta Air Lines",
  "American Eagle": "American Airlines",
  "United Express": "United Airlines",
  "Air France HOP": "Air France",
  "KLM cityhopper": "KLM Royal Dutch Airlines",
  "Lufthansa CityLine": "Lufthansa",
  "BA CityFlyer": "British Airways",
  "BA Euroflyer": "British Airways",
  "Iberia Express": "Iberia",
  "Iberia Regional": "Iberia",
  "Air Nostrum": "Iberia",
  "TAP Express": "TAP Air Portugal",
  "AeroMexico Connect": "AeroMexico",
  "Air Canada Express": "Air Canada",
  "easyJet UK": "easyJet",
  "easyJet Europe Airline": "easyJet",
  "Aer Lingus UK": "Aer Lingus",
  "Scandinavian Airlines Connect": "Scandinavian Airlines",
  "Scandinavian Airlines System": "Scandinavian Airlines",
  "LATAM Cargo Chile": "LATAM Airlines",
  "LATAM Peru": "LATAM Airlines",
};

export function slugifyAirlineName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

import { SEED_META } from "@/lib/seed";
import type { MessageKey } from "@/lib/i18n";

/** Registrations in SEED_META operated by this airline. */
export function trackedRegistrations(airlineName: string): string[] {
  return SEED_META.filter((m) => m.operator === airlineName).map(
    (m) => m.registration,
  );
}
