/**
 * Seed registrations for the sitemap and build-time static generation.
 *
 * Only registrations verified to resolve to a real aircraft fiche belong
 * here — every sitemap URL must return a 200 with content, otherwise it
 * hurts indexing instead of helping it. All entries below were verified
 * against the live lookup on 2026-09-22/23.
 *
 * Grow this list over time from Google Search Console: check which
 * registrations people search for ("Performance > Search results") and
 * add the ones that resolve.
 */
export const SEED_REGISTRATIONS = [
  // Homepage examples
  "F-HTYA",
  "A6-EUA",
  "G-ZBKA",
  "PH-BHA",
  "D-AIXA",
  "VH-OQA",
  // Verified popular airframes
  "G-BOAC",
  "F-BVFA",
  "D-ABYT",
  "A7-APA",
  "9V-SKQ",
  "JA873A",
  "N172DZ",
  "G-STBA",
  "F-HPJA",
  "4X-EDB",
  "A9C-FA",
  "HS-TQB",
  "9M-MAC",
  "B-LXI",
  "A6-BLA",
  "TC-LLB",
  "ET-AUP",
  "JA898A",
  "HL7644",
  "N661US",
  "D-ABVD",
  "G-BYGC",
  "A6-EOB",
  "A7-ALW",
  "9V-SKW",
  "HB-JNA",
  "LN-RKP",
  "OE-LPA",
  "OH-LWA",
  "OY-KBM",
  "PH-BXA",
  "SP-LRA",
  "TC-JJN",
  "VH-OQJ",
  "VT-ANB",
  "XA-ADL",
  "ZK-OKQ",
  "N501DN",
  "C-GHPQ",
  "F-GSPD",
  // Batch 2 — verified 2026-09-23
  "F-GZNQ",
  "F-GZNT",
  "A6-EOA",
  "A6-EOU",
  "G-BYGA",
  "G-CIVY",
  "D-AIGA",
  "VH-OQB",
  "9V-SKA",
  "JA789A",
  "HL7418",
  "TC-JJP",
  "A7-ALZ",
  "PH-BVA",
  "HB-JNB",
  "OE-LPE",
  "OH-LWB",
  "SP-LRB",
  "C-FNNQ",
  "N171DZ",
  "ZK-OKR",
  "VT-AND",
  "XA-ADG",
  "B-LXM",
  "9M-MAD",
  "ET-AVT",
  "A6-BLC",
  "HS-TQC",
  "4X-EDC",
  "A9C-FB",
  // Mass verification batch — 415 airframes verified 2026-09-23
  // concorde
  "F-BTSC",
  "F-BVFB",
  "F-BVFC",
  "F-BVFD",
  "F-BVFF",
  "F-WTSA",
  "F-WTSS",
  "G-AXDN",
  "G-BOAA",
  "G-BOAB",
  "G-BOAE",
  "G-BOAF",
  "G-BOAG",
  "G-BSST",
  // 747
  "9V-SPK",
  "B-18201",
  "B-18251",
  "B-2472",
  "D-ABTK",
  "D-ABTL",
  "D-ABVM",
  "D-ABVU",
  "D-ABVW",
  "D-ABVY",
  "D-ABVZ",
  "D-ABYA",
  "D-ABYC",
  "D-ABYF",
  "D-ABYG",
  "D-ABYJ",
  "D-ABYO",
  "D-ABYR",
  "D-ABYU",
  "F-BPVJ",
  "F-GITA",
  "F-GITD",
  "G-BNLA",
  "G-BNLK",
  "G-BNLY",
  "G-BYGB",
  "G-BYGE",
  "G-CIVA",
  "G-CIVH",
  "G-CIVO",
  "G-CIVR",
  "G-VAST",
  "G-VBIG",
  "G-VFAB",
  "G-VGAL",
  "G-VHOT",
  "G-VROS",
  "N171UA",
  "N601US",
  "N642NW",
  "N663US",
  "N667US",
  "N7470",
  "N747BC",
  "N747GE",
  "N747GF",
  "N908AR",
  "PH-BFB",
  "PH-BUK",
  "VH-OEE",
  "VH-OEH",
  "VH-OJA",
  "VH-OJJ",
  "VH-OJS",
  "VH-OJT",
  "ZS-SAN",
  "ZS-SPC",
  // 767
  "4X-EAA",
  "4X-EAK",
  "C-FPCA",
  "C-GAUB",
  "C-GHLU",
  "CC-CWF",
  "G-BNWA",
  "G-BZHA",
  "JA601J",
  "JA608A",
  "JA610J",
  "JA611A",
  "JA616J",
  "JA8285",
  "JA8971",
  "N101FE",
  "N111FE",
  "N126DL",
  "N130FE",
  "N169DZ",
  "N171DN",
  "N175DN",
  "N185DN",
  "N187DN",
  "N256AY",
  "N301AA",
  "N301UP",
  "N329UP",
  "N334UP",
  "N351AA",
  "N353AA",
  "N362UP",
  "N365UP",
  "N394DL",
  "N503KW",
  "N583HA",
  "N602TW",
  "N641UA",
  "N646UA",
  "N657UA",
  "N66051",
  "N661UA",
  "N664UA",
  "N668UA",
  "N676UA",
  "N828MH",
  "N843MH",
  "XA-TOJ",
  // 777
  "9V-SNA",
  "9V-SWA",
  "9V-SWH",
  "9V-SWK",
  "9V-SWM",
  "9V-SWN",
  "9V-SWT",
  "9V-SWU",
  "9V-SWV",
  "A6-EBF",
  "A6-EBH",
  "A6-EBO",
  "A6-ECA",
  "A6-ECF",
  "A6-ECK",
  "A6-ECY",
  "A6-EFD",
  "A6-EFH",
  "A6-EFS",
  "A6-EGT",
  "A6-EMX",
  "A6-ENE",
  "A6-EWA",
  "A6-EWI",
  "A7-BAA",
  "A7-BAC",
  "A7-BAG",
  "A7-BAJ",
  "A7-BAM",
  "A7-BAV",
  "A7-BAZ",
  "A7-BEG",
  "A7-BEO",
  "A7-BET",
  "B-HNI",
  "B-HNJ",
  "B-HNV",
  "B-KPA",
  "B-KPE",
  "B-KPJ",
  "B-KPR",
  "B-KPS",
  "B-KPW",
  "B-KQG",
  "G-STBB",
  "G-STBC",
  "G-STBF",
  "G-STBG",
  "G-STBK",
  "G-STBM",
  "JA751A",
  "JA753A",
  "JA756A",
  "JA784A",
  "JA795A",
  "N860DA",
  "N861DA",
  // 787
  "C-FNOE",
  "C-FNOG",
  "C-FNOI",
  "C-FRSA",
  "C-GHPT",
  "C-GHPV",
  "C-GHQQ",
  "ET-AOQ",
  "ET-AUQ",
  "ET-AUR",
  "ET-AXK",
  "ET-AXL",
  "G-ZBJA",
  "G-ZBJB",
  "G-ZBJD",
  "G-ZBJE",
  "G-ZBJI",
  "G-ZBKB",
  "G-ZBKL",
  "G-ZBLA",
  "G-ZBLH",
  "JA801A",
  "JA802A",
  "JA821J",
  "JA829J",
  "JA830A",
  "JA836J",
  "JA861J",
  "JA862J",
  "JA863J",
  "JA871J",
  "JA873J",
  "JA877A",
  "N17963",
  "N20904",
  "N26952",
  "N38950",
  "N38955",
  "N800AN",
  "N801AC",
  "N806AA",
  "N820AL",
  "N821AN",
  "N824AN",
  "SP-LRC",
  "SP-LRD",
  "SP-LRE",
  "SP-LRF",
  "SP-LSA",
  "SP-LSB",
  "VT-ANA",
  "VT-ANC",
  "VT-ANE",
  "VT-ANG",
  "VT-ANH",
  "VT-ANI",
  // a340
  "A6-EHJ",
  "A6-ERB",
  "A6-ERI",
  "D-AIFD",
  "D-AIGL",
  "D-AIGP",
  "D-AIGS",
  "D-AIGW",
  "D-AIHA",
  "D-AIHE",
  "D-AIHT",
  "D-AIHZ",
  "EC-INO",
  "EC-JBA",
  "F-GLZJ",
  "F-GLZN",
  "F-GLZP",
  "G-VATL",
  "G-VSHY",
  "G-VWKD",
  "HB-JMA",
  "HB-JMH",
  "HB-JMI",
  "ZS-SNE",
  "ZS-SXA",
  "ZS-SXD",
  // a350
  "9M-MAB",
  "9V-SGA",
  "9V-SMC",
  "9V-SMM",
  "9V-SMT",
  "9V-SMV",
  "A6-EXA",
  "A6-EXB",
  "A7-ALA",
  "A7-ALH",
  "A7-AMG",
  "A7-AML",
  "A7-ANA",
  "B-18901",
  "B-18902",
  "B-LQA",
  "B-LRA",
  "B-LRC",
  "B-LRO",
  "B-LRV",
  "D-AIXC",
  "D-AIXG",
  "D-AIXL",
  "D-AIXP",
  "EC-MXV",
  "EC-NBE",
  "F-HTYB",
  "F-HTYE",
  "F-HTYO",
  "G-VLIB",
  "G-VLUX",
  "G-XWBA",
  "G-XWBC",
  "G-XWBI",
  "JA01XJ",
  "JA02XJ",
  "N502DN",
  "N503DN",
  "N510DN",
  "OH-LWD",
  "OH-LWP",
  "TC-LGA",
  "TC-LGO",
  // a380
  "9M-MNA",
  "9M-MNF",
  "9V-SKB",
  "9V-SKF",
  "9V-SKI",
  "9V-SKP",
  "9V-SKY",
  "A6-APA",
  "A6-APB",
  "A6-APC",
  "A6-EDA",
  "A6-EDC",
  "A6-EDG",
  "A6-EDJ",
  "A6-EDN",
  "A6-EDR",
  "A6-EDX",
  "A6-EEE",
  "A7-APB",
  "A7-APC",
  "A7-APE",
  "A7-APG",
  "A7-APJ",
  "B-6136",
  "B-6137",
  "D-AIMA",
  "D-AIMB",
  "D-AIMD",
  "D-AIMI",
  "D-AIMK",
  "D-AIMM",
  "F-HPJB",
  "F-HPJG",
  "F-HPJJ",
  "G-XLEA",
  "G-XLEB",
  "G-XLEC",
  "G-XLED",
  "HL7611",
  "HL7612",
  "HL7625",
  "HL7626",
  "HS-TUA",
  "HS-TUB",
  "HS-TUC",
  "JA381A",
  "JA382A",
  "VH-OQC",
  "VH-OQD",
  "VH-OQF",
  "VH-OQG",
  // 737
  "C-FWVJ",
  "C-GJWS",
  "C-GKWJ",
  "C-GWSR",
  "C-GWSV",
  "D-ABKI",
  "D-AMAD",
  "D-AMAH",
  "D-AMAY",
  "D-AMAZ",
  "EI-DCJ",
  "EI-DCM",
  "EI-DCN",
  "EI-DCO",
  "EI-FRE",
  "G-DRTA",
  "G-DRTB",
  "G-DRTC",
  "G-DRTK",
  "G-DRTV",
  "LN-NIP",
  "LN-NOL",
  "LN-NOV",
  "N17753",
  "N200WN",
  "N201LV",
  "N371DA",
  "N372DA",
  "N3730B",
  "N3731T",
  "N3744F",
  "N506AS",
  "N508AS",
  "N512AS",
  "N516AS",
  "N517AS",
  "N7723E",
  "N77537",
  "N77539",
  "N79541",
  "N819NN",
  "N820SY",
  "N821SY",
  "N823NN",
  "N824SY",
  "N827SY",
  "N837SY",
  "N8576Z",
  "N8695D",
  "N8696E",
  "N901AN",
  "N902AN",
  "N903AN",
  "PH-BXB",
  "PH-BXC",
  "PH-BXD",
  "PH-BXE",
  "PH-BXF",
  "VH-VXA",
  "VH-VXB",
  "VH-VXC",
  "VH-VXP",
  "VH-VXT",
  // 737
  "G-DRTN",
  "G-JZHK",
  "G-TAWC",
  "N579UA",
  "VH-YFG",
  // 757
  "G-LSAA",
  "G-LSAB",
  "G-LSAC",
  "G-LSAD",
  "G-LSAL",
  "G-LSAN",
  "N189AN",
  "N405UP",
  "N412UP",
  "N413UP",
  "N420UP",
  "N427UP",
  "N433UP",
  "N434UP",
  "N446UP",
  "N452UP",
  "N459UP",
  "N472UP",
  "N521UA",
  "N523UA",
  "N529UA",
  "N532UA",
  "N540UA",
  "N546UA",
  "N551UA",
  "N556UA",
  "N565UA",
  "N583NW",
  "N585UA",
  "N594NW",
  "N605AA",
  "N608DA",
  "N609AA",
  "N614DL",
  "N625DL",
  "N630AA",
  "N633AA",
  "N648AA",
  "N652DL",
  "N653A",
  "N658DL",
  "N6713Y",
  "N672AA",
  "N674DL",
  "N677AN",
  "N695AN",
  "N709TW",
  "N712TW",
  "N752NA",
  "N790FD",
  "N903FD",
  "N909FD",
  "N910FD",
  "N915FD",
  "N919FD",
  "N923FD",
  "N927FD",
  "N959FD",
  "N962FD",
  "N967FD",
  "N968FD",
  "TF-FIG",
  "TF-FII",
  "TF-FIJ",
  "TF-FIN",
  "TF-FIR",
  "TF-FIS",
  "TF-ISK",
  "TF-ISR",
  "TF-ISS",
  "TF-ISY",
  "TF-LLX",
  // 767
  "N534LA",
  "VH-OGD",
  // 777
  "TC-LJO",
  // a320
  "A6-EIB",
  "A6-EII",
  "A6-EIK",
  "A6-EIL",
  "A6-EIP",
  "A6-EIX",
  "A6-EIY",
  "A7-AAG",
  "A7-AHB",
  "A7-AHP",
  "A7-AHW",
  "A7-AHX",
  "A7-AHY",
  "A7-LAG",
  "B-2351",
  "B-2376",
  "B-2377",
  "B-305J",
  "B-6276",
  "B-6292",
  "B-6677",
  "B-6679",
  "B-6911",
  "B-6918",
  "B-6976",
  "B-9925",
  "C-FGYL",
  "C-FKCO",
  "C-FPWE",
  "C-FTJQ",
  "C-GQCA",
  "CC-BFO",
  "CS-TNK",
  "CS-TNU",
  "CS-TVB",
  "CS-TVH",
  "CS-TVK",
  "D-AIPK",
  "D-AIQD",
  "D-AIQF",
  "D-AIUM",
  "D-AIUO",
  "D-AIWA",
  "D-AIWH",
  "EC-FDA",
  "EC-HUL",
  "EC-ILR",
  "EC-KAX",
  "EC-KOH",
  "EC-LVB",
  "EC-LVQ",
  "EC-LVS",
  "EC-LXQ",
  "EC-MAO",
  "EC-MBS",
  "EC-MUF",
  "EC-NTP",
  "EC-ODM",
  "EI-DEB",
  "EI-DEC",
  "EI-DEH",
  "EI-DEN",
  "EI-DER",
  "EI-DTM",
  "EI-DVE",
  "EI-EDP",
  "EI-EZW",
  "EI-SIC",
  "EI-SIK",
  "EI-SIY",
  "F-GFKY",
  "F-GJVC",
  "F-GJVG",
  "F-GKXJ",
  "F-HBNE",
  "F-HEPI",
  "G-EJCA",
  "G-EUUE",
  "G-EUYA",
  "G-EUYP",
  "G-EUYT",
  "G-EZPV",
  "G-EZTG",
  "G-GATP",
  "G-MIDO",
  "G-UZHZ",
  "HA-LJB",
  "HA-LYV",
  "HB-IJD",
  "HB-IJE",
  "HB-IJO",
  "HB-IJP",
  "HB-IJS",
  "HB-IJW",
  "N314US",
  "N333NW",
  "N336NW",
  "N355NW",
  "N356NW",
  "N377NW",
  "N378NW",
  "N440UA",
  "N448UA",
  "N474UA",
  "N534JB",
  "N536JB",
  "N549VL",
  "N623VA",
  "N636VA",
  "N641VA",
  "N657AW",
  "N661JB",
  "N673AW",
  "N703JB",
  "N729JB",
  "N763AV",
  "N768JB",
  "N809JB",
  "N844VA",
  "N846VA",
  "N966AV",
  "OE-ICP",
  "OE-IVL",
  "OE-LBI",
  "OE-LBL",
  "OE-LBW",
  "OE-LBZ",
  "OE-LXA",
  "OE-LXC",
  "OE-LZA",
  "OE-LZB",
  "OH-LXB",
  "OH-LXF",
  "OH-LXG",
  "OH-LXL",
  "OH-LXM",
  "OY-KAO",
  "OY-KAT",
  "SE-ROS",
  "SE-ROZ",
  "SE-RZY",
  // a330
  "9M-MKJ",
  "9M-MKV",
  "9M-MTL",
  "9M-MTX",
  "A6-AFA",
  "A6-AFD",
  "A7-ACJ",
  "A7-AEC",
  "A7-AEE",
  "A7-AEJ",
  "A7-AFV",
  "B-18305",
  "B-18310",
  "B-18315",
  "C-GEGC",
  "C-GFUR",
  "C-GHKW",
  "C-GHKX",
  "C-GHLM",
  "CS-TOE",
  "CS-TOG",
  "CS-TOO",
  "CS-TOS",
  "D-AIKK",
  "D-AIKL",
  "D-AIKN",
  "D-AIKP",
  "EC-LZX",
  "EC-MJA",
  "EC-MLP",
  "EC-MMG",
  "EC-NEN",
  "EI-DUB",
  "EI-ELA",
  "EI-GAJ",
  "F-GZCD",
  "F-GZCG",
  "F-GZCJ",
  "F-GZCL",
  "F-GZCO",
  "G-EILA",
  "G-VKSS",
  "G-VLUV",
  "G-VSRB",
  "G-VWAG",
  "HB-IQH",
  "HB-IQI",
  "HB-IQQ",
  "HB-JHL",
  "HL7524",
  "HL7586",
  "HL7747",
  "HL7792",
  "HL7793",
  "HL8027",
  "HL8211",
  "HL8259",
  "HL8282",
  "HS-TBC",
  "HS-TEP",
  "LN-RKS",
  "LN-RKT",
  "LN-RKU",
  "N407DX",
  "N829NW",
  "N859NW",
  "N860NW",
  "OH-LTN",
  "OH-LTO",
  "OH-LTP",
  "OH-LTU",
  "OY-VKF",
  "PH-AKE",
  "PH-AOC",
  "PH-AOM",
  "PH-AON",
  "SE-REH",
  "TC-JND",
  "TC-LNG",
  "TC-LOH",
  "VH-EBI",
  "VH-EBM",
  "VH-EBS",
  "VH-QPD",
  // a380
  "D-AIMC",
  // e190
  "C-FHNY",
  "C-FLWE",
  "C-FMYV",
  "CS-TPP",
  "CS-TPQ",
  "CS-TPS",
  "CS-TPY",
  "CS-TPZ",
  "CS-TTY",
  "F-HBLE",
  "F-HBLG",
  "F-HBLH",
  "F-HBLI",
  "F-HBLK",
  "F-HBLM",
  "F-HBLN",
  "G-LCAC",
  "G-LCYK",
  "G-LCYN",
  "G-LCYT",
  "G-LCYX",
  "G-LCYZ",
  "N231JB",
  "N266JB",
  "N267JB",
  "N307JB",
  "N317JB",
  "N323JB",
  "N355JB",
  "OH-LKE",
  "OH-LKF",
  "OH-LKG",
  "OH-LKI",
  "OH-LKK",
  "OH-LKN",
  "OH-LKO",
  "PH-EXY",
  "PH-EZN",
  "PH-EZO",
  "PH-EZR",
  "PH-EZW",
  "SP-LNA",
  "SP-LNB",
  "SP-LNF",
  "SP-LNN",
  "SP-LNO",
  "SP-LNP",
  "XA-AAC",
  "XA-CAC",
  "XA-GAH",
  "XA-GAI",
  "XA-JAC",
  // crj
  "C-FDJA",
  "C-FVKM",
  "C-FWJT",
  "C-GDJZ",
  "C-GKEU",
  "C-GOJA",
  "D-ACJE",
  "D-ACKI",
  "D-ACNO",
  "D-ACNP",
  "D-ACNV",
  "D-ACPQ",
  "EC-HHI",
  "EC-JCL",
  "EC-JEN",
  "EC-LOX",
  "EC-MNQ",
  "EC-MQQ",
  "EI-FPC",
  "EI-FPD",
  "EI-FPW",
  "EI-GEA",
  "F-GRJQ",
  "F-GRJT",
  "F-GRZI",
  "F-HMLI",
  "F-HMLJ",
  "F-HMLO",
  "N298PQ",
  "N303PQ",
  "N310PQ",
  "N348PQ",
  "N732SK",
  "N752SK",
  "N780SK",
  "N804SK",
  "N827SK",
  "N830SK",
  "N910XJ",
  "N928XJ",
  "N933XJ",
  "N952SW",
  "OY-KFE",
  "OY-KFI",
] as const;

export type AircraftFamily =
  | "concorde"
  | "737"
  | "747"
  | "757"
  | "767"
  | "777"
  | "787"
  | "a320"
  | "a330"
  | "a340"
  | "a350"
  | "a380"
  | "e190"
  | "crj";

/** Normalize a free-form type string ("Boeing 787-9 Dreamliner") to a family. */
export function familyOf(type: string | undefined): AircraftFamily | null {
  if (!type) return null;
  const t = type.toLowerCase();
  if (t.includes("concorde")) return "concorde";
  if (t.includes("737")) return "737";
  if (t.includes("747")) return "747";
  if (t.includes("757")) return "757";
  if (t.includes("767")) return "767";
  if (t.includes("777")) return "777";
  if (t.includes("787")) return "787";
  if (t.includes("320")) return "a320";
  if (t.includes("330")) return "a330";
  if (t.includes("340")) return "a340";
  if (t.includes("350")) return "a350";
  if (t.includes("380")) return "a380";
  if (t.includes("crj")) return "crj";
  if (
    t.includes("e190") ||
    t.includes("e195") ||
    t.includes("erj") ||
    (t.includes("embraer") && /(170|175|190|195)/.test(t))
  )
    return "e190";
  return null;
}

export type SeedMeta = {
  registration: string;
  family: AircraftFamily;
  /** Operator as returned by the lookup ("" when unknown). */
  operator: string;
  /**
   * Build year when known — baked in by scripts/bake-seed-years.ts from the
   * live lookup. Used only for family age statistics; entries without a
   * year are excluded from the average.
   */
  yearBuilt?: number;
};

/** Metadata for similarity matching ("similar airframes" on fiches). */
export const SEED_META: SeedMeta[] = [
  { registration: "F-HTYA", family: "a350", operator: "Air France", yearBuilt: 2019 },
  { registration: "A6-EUA", family: "a380", operator: "Emirates Airline", yearBuilt: 2016 },
  { registration: "G-ZBKA", family: "787", operator: "British Airways", yearBuilt: 2015 },
  { registration: "PH-BHA", family: "787", operator: "KLM Royal Dutch Airlines", yearBuilt: 2015 },
  { registration: "D-AIXA", family: "a350", operator: "Lufthansa", yearBuilt: 2016 },
  { registration: "VH-OQA", family: "a380", operator: "Qantas", yearBuilt: 2008 },
  { registration: "G-BOAC", family: "concorde", operator: "British Airways", yearBuilt: 1975 },
  { registration: "F-BVFA", family: "concorde", operator: "Air France", yearBuilt: 1976 },
  { registration: "D-ABYT", family: "747", operator: "Lufthansa", yearBuilt: 2015 },
  { registration: "A7-APA", family: "a380", operator: "Qatar Airways", yearBuilt: 2013 },
  { registration: "9V-SKQ", family: "a380", operator: "Singapore Airlines", yearBuilt: 2011 },
  { registration: "JA873A", family: "787", operator: "All Nippon Airways", yearBuilt: 2015 },
  { registration: "N172DZ", family: "767", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "G-STBA", family: "777", operator: "British Airways", yearBuilt: 2010 },
  { registration: "F-HPJA", family: "a380", operator: "Air France", yearBuilt: 2010 },
  { registration: "4X-EDB", family: "787", operator: "EL AL", yearBuilt: 2017 },
  { registration: "A9C-FA", family: "787", operator: "Gulf Air", yearBuilt: 2018 },
  { registration: "HS-TQB", family: "787", operator: "Thai Airways International", yearBuilt: 2014 },
  { registration: "9M-MAC", family: "a350", operator: "Malaysia Airlines", yearBuilt: 2017 },
  { registration: "B-LXI", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2019 },
  { registration: "A6-BLA", family: "787", operator: "Etihad Airways", yearBuilt: 2014 },
  { registration: "TC-LLB", family: "787", operator: "Turkish Airlines", yearBuilt: 2019 },
  { registration: "ET-AUP", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2017 },
  { registration: "JA898A", family: "787", operator: "All Nippon Airways", yearBuilt: 2018 },
  { registration: "HL7644", family: "747", operator: "Korean Air", yearBuilt: 2017 },
  { registration: "N661US", family: "747", operator: "Northwest Airlines", yearBuilt: 1989 },
  { registration: "D-ABVD", family: "747", operator: "Lufthansa", yearBuilt: 1990 },
  { registration: "G-BYGC", family: "747", operator: "British Airways", yearBuilt: 1999 },
  { registration: "A6-EOB", family: "a380", operator: "Emirates Airline", yearBuilt: 2014 },
  { registration: "A7-ALW", family: "a350", operator: "Qatar Airways", yearBuilt: 2017 },
  { registration: "9V-SKW", family: "a380", operator: "Singapore Airlines", yearBuilt: 2017 },
  { registration: "HB-JNA", family: "777", operator: "Swiss International Air Lines", yearBuilt: 2015 },
  { registration: "LN-RKP", family: "a340", operator: "Scandinavian Airlines", yearBuilt: 1997 },
  { registration: "OE-LPA", family: "777", operator: "Austrian Airlines", yearBuilt: 1997 },
  { registration: "OH-LWA", family: "a350", operator: "Finnair", yearBuilt: 2015 },
  { registration: "OY-KBM", family: "a340", operator: "Scandinavian Airlines", yearBuilt: 2002 },
  { registration: "PH-BXA", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 1998 },
  { registration: "SP-LRA", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2012 },
  { registration: "TC-JJN", family: "777", operator: "Turkish Airlines", yearBuilt: 2011 },
  { registration: "VH-OQJ", family: "a380", operator: "Qantas", yearBuilt: 2010 },
  { registration: "VT-ANB", family: "787", operator: "Air India", yearBuilt: 2011 },
  { registration: "XA-ADL", family: "787", operator: "AeroMexico", yearBuilt: 2016 },
  { registration: "ZK-OKQ", family: "777", operator: "Air New Zealand", yearBuilt: 2011 },
  { registration: "N501DN", family: "a350", operator: "Delta Air Lines", yearBuilt: 2017 },
  { registration: "C-GHPQ", family: "787", operator: "Air Canada", yearBuilt: 2014 },
  { registration: "F-GSPD", family: "777", operator: "Air France", yearBuilt: 1998 },
  { registration: "F-GZNQ", family: "777", operator: "Air France", yearBuilt: 2015 },
  { registration: "F-GZNT", family: "777", operator: "Air France", yearBuilt: 2016 },
  { registration: "A6-EOA", family: "a380", operator: "Emirates Airline", yearBuilt: 2014 },
  { registration: "A6-EOU", family: "a380", operator: "Emirates Airline", yearBuilt: 2015 },
  { registration: "G-BYGA", family: "747", operator: "British Airways", yearBuilt: 1998 },
  { registration: "G-CIVY", family: "747", operator: "British Airways", yearBuilt: 1998 },
  { registration: "D-AIGA", family: "a340", operator: "Lufthansa", yearBuilt: 1993 },
  { registration: "VH-OQB", family: "a380", operator: "Qantas", yearBuilt: 2008 },
  { registration: "9V-SKA", family: "a380", operator: "Singapore Airlines", yearBuilt: 2007 },
  { registration: "JA789A", family: "777", operator: "All Nippon Airways", yearBuilt: 2010 },
  { registration: "HL7418", family: "747", operator: "Asiana Airlines", yearBuilt: 1994 },
  { registration: "TC-JJP", family: "777", operator: "Turkish Airlines", yearBuilt: 2011 },
  { registration: "A7-ALZ", family: "a350", operator: "Qatar Airways", yearBuilt: 2018 },
  { registration: "PH-BVA", family: "777", operator: "KLM Royal Dutch Airlines", yearBuilt: 2008 },
  { registration: "HB-JNB", family: "777", operator: "Swiss International Air Lines", yearBuilt: 2016 },
  { registration: "OE-LPE", family: "777", operator: "Austrian Airlines", yearBuilt: 1998 },
  { registration: "OH-LWB", family: "a350", operator: "Finnair", yearBuilt: 2015 },
  { registration: "SP-LRB", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2012 },
  { registration: "C-FNNQ", family: "777", operator: "Air Canada", yearBuilt: 2013 },
  { registration: "N171DZ", family: "767", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "ZK-OKR", family: "777", operator: "Air New Zealand", yearBuilt: 2014 },
  { registration: "VT-AND", family: "787", operator: "Air India", yearBuilt: 2011 },
  { registration: "XA-ADG", family: "787", operator: "AeroMexico", yearBuilt: 2017 },
  { registration: "B-LXM", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2020 },
  { registration: "9M-MAD", family: "a350", operator: "Malaysia Airlines", yearBuilt: 2018 },
  { registration: "ET-AVT", family: "777", operator: "Ethiopian Cargo", yearBuilt: 2018 },
  { registration: "A6-BLC", family: "787", operator: "Etihad Airways", yearBuilt: 2015 },
  { registration: "HS-TQC", family: "787", operator: "Thai Airways International", yearBuilt: 2014 },
  { registration: "4X-EDC", family: "787", operator: "EL AL", yearBuilt: 2018 },
  { registration: "A9C-FB", family: "787", operator: "Gulf Air", yearBuilt: 2018 },
  // Mass verification batch — 415 airframes verified 2026-09-23
  // concorde
  { registration: "F-BTSC", family: "concorde", operator: "Air France", yearBuilt: 1975 },
  { registration: "F-BVFB", family: "concorde", operator: "Air France", yearBuilt: 1976 },
  { registration: "F-BVFC", family: "concorde", operator: "Air France", yearBuilt: 1976 },
  { registration: "F-BVFD", family: "concorde", operator: "Air France", yearBuilt: 1977 },
  { registration: "F-BVFF", family: "concorde", operator: "Air France", yearBuilt: 1978 },
  { registration: "F-WTSA", family: "concorde", operator: "Air France", yearBuilt: 1973 },
  { registration: "F-WTSS", family: "concorde", operator: "Air France", yearBuilt: 1968 },
  { registration: "G-AXDN", family: "concorde", operator: "British Airways", yearBuilt: 1968 },
  { registration: "G-BOAA", family: "concorde", operator: "British Airways", yearBuilt: 1974 },
  { registration: "G-BOAB", family: "concorde", operator: "British Airways", yearBuilt: 1976 },
  { registration: "G-BOAE", family: "concorde", operator: "British Airways", yearBuilt: 1977 },
  { registration: "G-BOAF", family: "concorde", operator: "British Airways", yearBuilt: 1979 },
  { registration: "G-BOAG", family: "concorde", operator: "British Airways", yearBuilt: 1978 },
  { registration: "G-BSST", family: "concorde", operator: "British Airways", yearBuilt: 1966 },
  // 747
  { registration: "9V-SPK", family: "747", operator: "Singapore Airlines", yearBuilt: 1997 },
  { registration: "B-18201", family: "747", operator: "China Airlines", yearBuilt: 1997 },
  { registration: "B-18251", family: "747", operator: "China Airlines", yearBuilt: 1995 },
  { registration: "B-2472", family: "747", operator: "Air China", yearBuilt: 2000 },
  { registration: "D-ABTK", family: "747", operator: "Lufthansa", yearBuilt: 2001 },
  { registration: "D-ABTL", family: "747", operator: "Lufthansa", yearBuilt: 2002 },
  { registration: "D-ABVM", family: "747", operator: "Lufthansa", yearBuilt: 1998 },
  { registration: "D-ABVU", family: "747", operator: "Lufthansa", yearBuilt: 1998 },
  { registration: "D-ABVW", family: "747", operator: "Lufthansa", yearBuilt: 1999 },
  { registration: "D-ABVY", family: "747", operator: "Lufthansa", yearBuilt: 2000 },
  { registration: "D-ABVZ", family: "747", operator: "Lufthansa", yearBuilt: 2001 },
  { registration: "D-ABYA", family: "747", operator: "Lufthansa", yearBuilt: 2012 },
  { registration: "D-ABYC", family: "747", operator: "Lufthansa", yearBuilt: 2012 },
  { registration: "D-ABYF", family: "747", operator: "Lufthansa", yearBuilt: 2012 },
  { registration: "D-ABYG", family: "747", operator: "Lufthansa", yearBuilt: 2013 },
  { registration: "D-ABYJ", family: "747", operator: "Lufthansa", yearBuilt: 2013 },
  { registration: "D-ABYO", family: "747", operator: "Lufthansa", yearBuilt: 2014 },
  { registration: "D-ABYR", family: "747", operator: "Lufthansa", yearBuilt: 2014 },
  { registration: "D-ABYU", family: "747", operator: "Lufthansa", yearBuilt: 2015 },
  { registration: "F-BPVJ", family: "747", operator: "Air France", yearBuilt: 1972 },
  { registration: "F-GITA", family: "747", operator: "Air France", yearBuilt: 1991 },
  { registration: "F-GITD", family: "747", operator: "Air France", yearBuilt: 1992 },
  { registration: "G-BNLA", family: "747", operator: "British Airways", yearBuilt: 1989 },
  { registration: "G-BNLK", family: "747", operator: "British Airways", yearBuilt: 1990 },
  { registration: "G-BNLY", family: "747", operator: "British Airways", yearBuilt: 1993 },
  { registration: "G-BYGB", family: "747", operator: "British Airways", yearBuilt: 1999 },
  { registration: "G-BYGE", family: "747", operator: "British Airways", yearBuilt: 1999 },
  { registration: "G-CIVA", family: "747", operator: "British Airways", yearBuilt: 1993 },
  { registration: "G-CIVH", family: "747", operator: "British Airways", yearBuilt: 1996 },
  { registration: "G-CIVO", family: "747", operator: "British Airways", yearBuilt: 1997 },
  { registration: "G-CIVR", family: "747", operator: "British Airways", yearBuilt: 1998 },
  { registration: "G-VAST", family: "747", operator: "Virgin Atlantic", yearBuilt: 1997 },
  { registration: "G-VBIG", family: "747", operator: "Virgin Atlantic", yearBuilt: 1996 },
  { registration: "G-VFAB", family: "747", operator: "Virgin Atlantic", yearBuilt: 1994 },
  { registration: "G-VGAL", family: "747", operator: "Virgin Atlantic", yearBuilt: 2001 },
  { registration: "G-VHOT", family: "747", operator: "Virgin Atlantic", yearBuilt: 1994 },
  { registration: "G-VROS", family: "747", operator: "Virgin Atlantic", yearBuilt: 2001 },
  { registration: "N171UA", family: "747", operator: "United Airlines", yearBuilt: 1989 },
  { registration: "N601US", family: "747", operator: "Northwest Airlines", yearBuilt: 1970 },
  { registration: "N642NW", family: "747", operator: "Northwest Airlines", yearBuilt: 1980 },
  { registration: "N663US", family: "747", operator: "Delta Air Lines", yearBuilt: 1988 },
  { registration: "N667US", family: "747", operator: "Delta Air Lines", yearBuilt: 1990 },
  { registration: "N7470", family: "747", operator: "Boeing", yearBuilt: 1969 },
  { registration: "N747BC", family: "747", operator: "Boeing", yearBuilt: 1992 },
  { registration: "N747GE", family: "747", operator: "General Electric", yearBuilt: 1970 },
  { registration: "N747GF", family: "747", operator: "General Electric", yearBuilt: 1994 },
  { registration: "N908AR", family: "747", operator: "SkyLease Cargo", yearBuilt: 1997 },
  { registration: "PH-BFB", family: "747", operator: "KLM Royal Dutch Airlines", yearBuilt: 1989 },
  { registration: "PH-BUK", family: "747", operator: "KLM Royal Dutch Airlines", yearBuilt: 1978 },
  { registration: "VH-OEE", family: "747", operator: "Qantas", yearBuilt: 2002 },
  { registration: "VH-OEH", family: "747", operator: "Qantas", yearBuilt: 2003 },
  { registration: "VH-OJA", family: "747", operator: "Qantas", yearBuilt: 1989 },
  { registration: "VH-OJJ", family: "747", operator: "Qantas", yearBuilt: 1991 },
  { registration: "VH-OJS", family: "747", operator: "Qantas", yearBuilt: 1999 },
  { registration: "VH-OJT", family: "747", operator: "Qantas", yearBuilt: 1999 },
  { registration: "ZS-SAN", family: "747", operator: "South African Airways", yearBuilt: 1971 },
  { registration: "ZS-SPC", family: "747", operator: "South African Airways", yearBuilt: 1976 },
  // 767
  { registration: "4X-EAA", family: "767", operator: "EL AL", yearBuilt: 1983 },
  { registration: "4X-EAK", family: "767", operator: "EL AL", yearBuilt: 1997 },
  { registration: "C-FPCA", family: "767", operator: "Air Canada", yearBuilt: 1989 },
  { registration: "C-GAUB", family: "767", operator: "Air Canada", yearBuilt: 1982 },
  { registration: "C-GHLU", family: "767", operator: "Air Canada", yearBuilt: 2001 },
  { registration: "CC-CWF", family: "767", operator: "LATAM Airlines", yearBuilt: 2006 },
  { registration: "G-BNWA", family: "767", operator: "British Airways", yearBuilt: 1989 },
  { registration: "G-BZHA", family: "767", operator: "British Airways", yearBuilt: 1998 },
  { registration: "JA601J", family: "767", operator: "Japan Airlines", yearBuilt: 2002 },
  { registration: "JA608A", family: "767", operator: "All Nippon Airways", yearBuilt: 2002 },
  { registration: "JA610J", family: "767", operator: "Japan Airlines", yearBuilt: 2004 },
  { registration: "JA611A", family: "767", operator: "All Nippon Airways", yearBuilt: 2003 },
  { registration: "JA616J", family: "767", operator: "Japan Airlines", yearBuilt: 2007 },
  { registration: "JA8285", family: "767", operator: "All Nippon Airways", yearBuilt: 1988 },
  { registration: "JA8971", family: "767", operator: "All Nippon Airways", yearBuilt: 1997 },
  { registration: "N101FE", family: "767", operator: "FedEx Express", yearBuilt: 2013 },
  { registration: "N111FE", family: "767", operator: "FedEx Express", yearBuilt: 2020 },
  { registration: "N126DL", family: "767", operator: "Delta Air Lines", yearBuilt: 1988 },
  { registration: "N130FE", family: "767", operator: "FedEx Express", yearBuilt: 2016 },
  { registration: "N169DZ", family: "767", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "N171DN", family: "767", operator: "Delta Air Lines", yearBuilt: 1990 },
  { registration: "N175DN", family: "767", operator: "Delta Air Lines", yearBuilt: 1990 },
  { registration: "N185DN", family: "767", operator: "Delta Air Lines", yearBuilt: 1995 },
  { registration: "N187DN", family: "767", operator: "Delta Air Lines", yearBuilt: 1996 },
  { registration: "N256AY", family: "767", operator: "US Airways", yearBuilt: 1993 },
  { registration: "N301AA", family: "767", operator: "American Airlines", yearBuilt: 1982 },
  { registration: "N301UP", family: "767", operator: "UPS", yearBuilt: 1995 },
  { registration: "N329UP", family: "767", operator: "UPS", yearBuilt: 1999 },
  { registration: "N334UP", family: "767", operator: "UPS", yearBuilt: 2001 },
  { registration: "N351AA", family: "767", operator: "American Airlines", yearBuilt: 1988 },
  { registration: "N353AA", family: "767", operator: "American Airlines", yearBuilt: 1988 },
  { registration: "N362UP", family: "767", operator: "UPS", yearBuilt: 2003 },
  { registration: "N365UP", family: "767", operator: "UPS", yearBuilt: 2019 },
  { registration: "N394DL", family: "767", operator: "Delta Air Lines", yearBuilt: 1995 },
  { registration: "N503KW", family: "767", operator: "Eastern Airlines", yearBuilt: 1998 },
  { registration: "N583HA", family: "767", operator: "Hawaiian Airlines", yearBuilt: 1992 },
  { registration: "N602TW", family: "767", operator: "TWA", yearBuilt: 1982 },
  { registration: "N641UA", family: "767", operator: "United Airlines", yearBuilt: 1991 },
  { registration: "N646UA", family: "767", operator: "United Airlines", yearBuilt: 1992 },
  { registration: "N657UA", family: "767", operator: "United Airlines", yearBuilt: 1993 },
  { registration: "N66051", family: "767", operator: "United Airlines", yearBuilt: 2000 },
  { registration: "N661UA", family: "767", operator: "United Airlines", yearBuilt: 1993 },
  { registration: "N664UA", family: "767", operator: "United Airlines", yearBuilt: 1998 },
  { registration: "N668UA", family: "767", operator: "United Airlines", yearBuilt: 1999 },
  { registration: "N676UA", family: "767", operator: "United Airlines", yearBuilt: 2001 },
  { registration: "N828MH", family: "767", operator: "Delta Air Lines", yearBuilt: 2000 },
  { registration: "N843MH", family: "767", operator: "Delta Air Lines", yearBuilt: 2002 },
  { registration: "XA-TOJ", family: "767", operator: "AeroMexico", yearBuilt: 1990 },
  // 777
  { registration: "9V-SNA", family: "777", operator: "Singapore Airlines", yearBuilt: 2015 },
  { registration: "9V-SWA", family: "777", operator: "Singapore Airlines", yearBuilt: 2006 },
  { registration: "9V-SWH", family: "777", operator: "Singapore Airlines", yearBuilt: 2007 },
  { registration: "9V-SWK", family: "777", operator: "Singapore Airlines", yearBuilt: 2007 },
  { registration: "9V-SWM", family: "777", operator: "Singapore Airlines", yearBuilt: 2008 },
  { registration: "9V-SWN", family: "777", operator: "Singapore Airlines", yearBuilt: 2008 },
  { registration: "9V-SWT", family: "777", operator: "Singapore Airlines", yearBuilt: 2009 },
  { registration: "9V-SWU", family: "777", operator: "Singapore Airlines", yearBuilt: 2013 },
  { registration: "9V-SWV", family: "777", operator: "Singapore Airlines", yearBuilt: 2013 },
  { registration: "A6-EBF", family: "777", operator: "Emirates Airline", yearBuilt: 2005 },
  { registration: "A6-EBH", family: "777", operator: "Emirates Airline", yearBuilt: 2005 },
  { registration: "A6-EBO", family: "777", operator: "Emirates Airline", yearBuilt: 2006 },
  { registration: "A6-ECA", family: "777", operator: "Emirates Airline", yearBuilt: 2006 },
  { registration: "A6-ECF", family: "777", operator: "Emirates Airline", yearBuilt: 2007 },
  { registration: "A6-ECK", family: "777", operator: "Emirates Airline", yearBuilt: 2008 },
  { registration: "A6-ECY", family: "777", operator: "Emirates Airline", yearBuilt: 2009 },
  { registration: "A6-EFD", family: "777", operator: "Emirates Airline", yearBuilt: 2009 },
  { registration: "A6-EFH", family: "777", operator: "Emirates Airline", yearBuilt: 2012 },
  { registration: "A6-EFS", family: "777", operator: "Emirates Airline", yearBuilt: 2015 },
  { registration: "A6-EGT", family: "777", operator: "Emirates Airline", yearBuilt: 2012 },
  { registration: "A6-EMX", family: "777", operator: "Emirates Airline", yearBuilt: 2003 },
  { registration: "A6-ENE", family: "777", operator: "Emirates Airline", yearBuilt: 2013 },
  { registration: "A6-EWA", family: "777", operator: "Emirates Airline", yearBuilt: 2007 },
  { registration: "A6-EWI", family: "777", operator: "Emirates Airline", yearBuilt: 2008 },
  { registration: "A7-BAA", family: "777", operator: "Qatar Airways", yearBuilt: 2007 },
  { registration: "A7-BAC", family: "777", operator: "Qatar Airways", yearBuilt: 2008 },
  { registration: "A7-BAG", family: "777", operator: "Qatar Airways", yearBuilt: 2009 },
  { registration: "A7-BAJ", family: "777", operator: "Qatar Airways", yearBuilt: 2010 },
  { registration: "A7-BAM", family: "777", operator: "Qatar Airways", yearBuilt: 2011 },
  { registration: "A7-BAV", family: "777", operator: "Qatar Airways", yearBuilt: 2014 },
  { registration: "A7-BAZ", family: "777", operator: "Qatar Airways", yearBuilt: 2013 },
  { registration: "A7-BEG", family: "777", operator: "Qatar Airways", yearBuilt: 2015 },
  { registration: "A7-BEO", family: "777", operator: "Qatar Airways", yearBuilt: 2017 },
  { registration: "A7-BET", family: "777", operator: "Qatar Airways", yearBuilt: 2018 },
  { registration: "B-HNI", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 1999 },
  { registration: "B-HNJ", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 1999 },
  { registration: "B-HNV", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2019 },
  { registration: "B-KPA", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2007 },
  { registration: "B-KPE", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2007 },
  { registration: "B-KPJ", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2008 },
  { registration: "B-KPR", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2010 },
  { registration: "B-KPS", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2011 },
  { registration: "B-KPW", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2011 },
  { registration: "B-KQG", family: "777", operator: "Cathay Pacific Airways", yearBuilt: 2013 },
  { registration: "G-STBB", family: "777", operator: "British Airways", yearBuilt: 2010 },
  { registration: "G-STBC", family: "777", operator: "British Airways", yearBuilt: 2010 },
  { registration: "G-STBF", family: "777", operator: "British Airways", yearBuilt: 2012 },
  { registration: "G-STBG", family: "777", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-STBK", family: "777", operator: "British Airways", yearBuilt: 2014 },
  { registration: "G-STBM", family: "777", operator: "British Airways", yearBuilt: 2020 },
  { registration: "JA751A", family: "777", operator: "All Nippon Airways", yearBuilt: 1998 },
  { registration: "JA753A", family: "777", operator: "All Nippon Airways", yearBuilt: 1998 },
  { registration: "JA756A", family: "777", operator: "All Nippon Airways", yearBuilt: 2003 },
  { registration: "JA784A", family: "777", operator: "All Nippon Airways", yearBuilt: 2009 },
  { registration: "JA795A", family: "777", operator: "All Nippon Airways", yearBuilt: 2019 },
  { registration: "N860DA", family: "777", operator: "Gridiron Air", yearBuilt: 1999 },
  { registration: "N861DA", family: "777", operator: "Delta Air Lines", yearBuilt: 1999 },
  // 787
  { registration: "C-FNOE", family: "787", operator: "Air Canada", yearBuilt: 2015 },
  { registration: "C-FNOG", family: "787", operator: "Air Canada", yearBuilt: 2015 },
  { registration: "C-FNOI", family: "787", operator: "Air Canada", yearBuilt: 2015 },
  { registration: "C-FRSA", family: "787", operator: "Air Canada", yearBuilt: 2017 },
  { registration: "C-GHPT", family: "787", operator: "Air Canada", yearBuilt: 2014 },
  { registration: "C-GHPV", family: "787", operator: "Air Canada", yearBuilt: 2014 },
  { registration: "C-GHQQ", family: "787", operator: "Air Canada", yearBuilt: 2014 },
  { registration: "ET-AOQ", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2012 },
  { registration: "ET-AUQ", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2018 },
  { registration: "ET-AUR", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2018 },
  { registration: "ET-AXK", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2019 },
  { registration: "ET-AXL", family: "787", operator: "Ethiopian Airlines", yearBuilt: 2019 },
  { registration: "G-ZBJA", family: "787", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-ZBJB", family: "787", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-ZBJD", family: "787", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-ZBJE", family: "787", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-ZBJI", family: "787", operator: "British Airways", yearBuilt: 2017 },
  { registration: "G-ZBKB", family: "787", operator: "British Airways", yearBuilt: 2015 },
  { registration: "G-ZBKL", family: "787", operator: "British Airways", yearBuilt: 2016 },
  { registration: "G-ZBLA", family: "787", operator: "British Airways", yearBuilt: 2019 },
  { registration: "G-ZBLH", family: "787", operator: "British Airways", yearBuilt: 2024 },
  { registration: "JA801A", family: "787", operator: "Air Japan", yearBuilt: 2011 },
  { registration: "JA802A", family: "787", operator: "All Nippon Airways", yearBuilt: 2011 },
  { registration: "JA821J", family: "787", operator: "Japan Airlines", yearBuilt: 2010 },
  { registration: "JA829J", family: "787", operator: "Japan Airlines", yearBuilt: 2012 },
  { registration: "JA830A", family: "787", operator: "All Nippon Airways", yearBuilt: 2014 },
  { registration: "JA836J", family: "787", operator: "Japan Airlines", yearBuilt: 2014 },
  { registration: "JA861J", family: "787", operator: "Japan Airlines", yearBuilt: 2013 },
  { registration: "JA862J", family: "787", operator: "Japan Airlines", yearBuilt: 2015 },
  { registration: "JA863J", family: "787", operator: "Japan Airlines", yearBuilt: 2016 },
  { registration: "JA871J", family: "787", operator: "Japan Airlines", yearBuilt: 2017 },
  { registration: "JA873J", family: "787", operator: "Japan Airlines", yearBuilt: 2018 },
  { registration: "JA877A", family: "787", operator: "All Nippon Airways", yearBuilt: 2016 },
  { registration: "N17963", family: "787", operator: "United Airlines", yearBuilt: 2016 },
  { registration: "N20904", family: "787", operator: "United Airlines", yearBuilt: 2012 },
  { registration: "N26952", family: "787", operator: "United Airlines", yearBuilt: 2014 },
  { registration: "N38950", family: "787", operator: "United Airlines", yearBuilt: 2014 },
  { registration: "N38955", family: "787", operator: "United Airlines", yearBuilt: 2015 },
  { registration: "N800AN", family: "787", operator: "American Airlines", yearBuilt: 2014 },
  { registration: "N801AC", family: "787", operator: "American Airlines", yearBuilt: 2015 },
  { registration: "N806AA", family: "787", operator: "American Airlines", yearBuilt: 2015 },
  { registration: "N820AL", family: "787", operator: "American Airlines", yearBuilt: 2016 },
  { registration: "N821AN", family: "787", operator: "American Airlines", yearBuilt: 2016 },
  { registration: "N824AN", family: "787", operator: "American Airlines", yearBuilt: 2017 },
  { registration: "SP-LRC", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2013 },
  { registration: "SP-LRD", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2013 },
  { registration: "SP-LRE", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2013 },
  { registration: "SP-LRF", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2014 },
  { registration: "SP-LSA", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2018 },
  { registration: "SP-LSB", family: "787", operator: "LOT Polish Airlines", yearBuilt: 2018 },
  { registration: "VT-ANA", family: "787", operator: "Air India", yearBuilt: 2011 },
  { registration: "VT-ANC", family: "787", operator: "Air India", yearBuilt: 2010 },
  { registration: "VT-ANE", family: "787", operator: "Air India", yearBuilt: 2013 },
  { registration: "VT-ANG", family: "787", operator: "Air India", yearBuilt: 2011 },
  { registration: "VT-ANH", family: "787", operator: "Air India", yearBuilt: 2012 },
  { registration: "VT-ANI", family: "787", operator: "Air India", yearBuilt: 2012 },
  // a340
  { registration: "A6-EHJ", family: "a340", operator: "Etihad Airways", yearBuilt: 2008 },
  { registration: "A6-ERB", family: "a340", operator: "Emirates Airline", yearBuilt: 2003 },
  { registration: "A6-ERI", family: "a340", operator: "Emirates Airline", yearBuilt: 2005 },
  { registration: "D-AIFD", family: "a340", operator: "Lufthansa", yearBuilt: 2001 },
  { registration: "D-AIGL", family: "a340", operator: "Lufthansa", yearBuilt: 1996 },
  { registration: "D-AIGP", family: "a340", operator: "Lufthansa", yearBuilt: 1998 },
  { registration: "D-AIGS", family: "a340", operator: "Lufthansa", yearBuilt: 1999 },
  { registration: "D-AIGW", family: "a340", operator: "Lufthansa", yearBuilt: 2000 },
  { registration: "D-AIHA", family: "a340", operator: "Lufthansa", yearBuilt: 2003 },
  { registration: "D-AIHE", family: "a340", operator: "Lufthansa", yearBuilt: 2003 },
  { registration: "D-AIHT", family: "a340", operator: "Lufthansa", yearBuilt: 2008 },
  { registration: "D-AIHZ", family: "a340", operator: "Lufthansa", yearBuilt: 2009 },
  { registration: "EC-INO", family: "a340", operator: "Iberia", yearBuilt: 2003 },
  { registration: "EC-JBA", family: "a340", operator: "Iberia", yearBuilt: 2004 },
  { registration: "F-GLZJ", family: "a340", operator: "Air France", yearBuilt: 1997 },
  { registration: "F-GLZN", family: "a340", operator: "Air France", yearBuilt: 1998 },
  { registration: "F-GLZP", family: "a340", operator: "Air France", yearBuilt: 1999 },
  { registration: "G-VATL", family: "a340", operator: "Virgin Atlantic", yearBuilt: 2001 },
  { registration: "G-VSHY", family: "a340", operator: "Virgin Atlantic", yearBuilt: 2002 },
  { registration: "G-VWKD", family: "a340", operator: "Virgin Atlantic", yearBuilt: 2005 },
  { registration: "HB-JMA", family: "a340", operator: "Swiss International Air Lines", yearBuilt: 2003 },
  { registration: "HB-JMH", family: "a340", operator: "Swiss International Air Lines", yearBuilt: 2004 },
  { registration: "HB-JMI", family: "a340", operator: "Swiss International Air Lines", yearBuilt: 2004 },
  { registration: "ZS-SNE", family: "a340", operator: "South African Airways", yearBuilt: 2003 },
  { registration: "ZS-SXA", family: "a340", operator: "South African Airways", yearBuilt: 2003 },
  { registration: "ZS-SXD", family: "a340", operator: "South African Airways", yearBuilt: 2004 },
  // a350
  { registration: "9M-MAB", family: "a350", operator: "Malaysia Airlines", yearBuilt: 2017 },
  { registration: "9V-SGA", family: "a350", operator: "Singapore Airlines", yearBuilt: 2018 },
  { registration: "9V-SMC", family: "a350", operator: "Singapore Airlines", yearBuilt: 2016 },
  { registration: "9V-SMM", family: "a350", operator: "Singapore Airlines", yearBuilt: 2017 },
  { registration: "9V-SMT", family: "a350", operator: "Singapore Airlines", yearBuilt: 2017 },
  { registration: "9V-SMV", family: "a350", operator: "Singapore Airlines", yearBuilt: 2019 },
  { registration: "A6-EXA", family: "a350", operator: "Emirates Airline", yearBuilt: 2024 },
  { registration: "A6-EXB", family: "a350", operator: "Emirates Airline", yearBuilt: 2024 },
  { registration: "A7-ALA", family: "a350", operator: "Qatar Airways", yearBuilt: 2014 },
  { registration: "A7-ALH", family: "a350", operator: "Qatar Airways", yearBuilt: 2015 },
  { registration: "A7-AMG", family: "a350", operator: "Qatar Airways", yearBuilt: 2018 },
  { registration: "A7-AML", family: "a350", operator: "Qatar Airways", yearBuilt: 2019 },
  { registration: "A7-ANA", family: "a350", operator: "Qatar Airways", yearBuilt: 2017 },
  { registration: "B-18901", family: "a350", operator: "China Airlines", yearBuilt: 2016 },
  { registration: "B-18902", family: "a350", operator: "China Airlines", yearBuilt: 2016 },
  { registration: "B-LQA", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2019 },
  { registration: "B-LRA", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2016 },
  { registration: "B-LRC", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2016 },
  { registration: "B-LRO", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2017 },
  { registration: "B-LRV", family: "a350", operator: "Cathay Pacific Airways", yearBuilt: 2017 },
  { registration: "D-AIXC", family: "a350", operator: "Lufthansa", yearBuilt: 2017 },
  { registration: "D-AIXG", family: "a350", operator: "Lufthansa", yearBuilt: 2017 },
  { registration: "D-AIXL", family: "a350", operator: "Lufthansa", yearBuilt: 2018 },
  { registration: "D-AIXP", family: "a350", operator: "Lufthansa", yearBuilt: 2020 },
  { registration: "EC-MXV", family: "a350", operator: "Iberia", yearBuilt: 2018 },
  { registration: "EC-NBE", family: "a350", operator: "Iberia", yearBuilt: 2019 },
  { registration: "F-HTYB", family: "a350", operator: "Air France", yearBuilt: 2019 },
  { registration: "F-HTYE", family: "a350", operator: "Air France", yearBuilt: 2020 },
  { registration: "F-HTYO", family: "a350", operator: "Air France", yearBuilt: 2022 },
  { registration: "G-VLIB", family: "a350", operator: "Virgin Atlantic", yearBuilt: 2022 },
  { registration: "G-VLUX", family: "a350", operator: "Virgin Atlantic", yearBuilt: 2019 },
  { registration: "G-XWBA", family: "a350", operator: "British Airways", yearBuilt: 2019 },
  { registration: "G-XWBC", family: "a350", operator: "British Airways", yearBuilt: 2019 },
  { registration: "G-XWBI", family: "a350", operator: "British Airways", yearBuilt: 2021 },
  { registration: "JA01XJ", family: "a350", operator: "Japan Airlines", yearBuilt: 2019 },
  { registration: "JA02XJ", family: "a350", operator: "Japan Airlines", yearBuilt: 2019 },
  { registration: "N502DN", family: "a350", operator: "Delta Air Lines", yearBuilt: 2017 },
  { registration: "N503DN", family: "a350", operator: "Delta Air Lines", yearBuilt: 2017 },
  { registration: "N510DN", family: "a350", operator: "Delta Air Lines", yearBuilt: 2018 },
  { registration: "OH-LWD", family: "a350", operator: "Finnair", yearBuilt: 2015 },
  { registration: "OH-LWP", family: "a350", operator: "Finnair", yearBuilt: 2019 },
  { registration: "TC-LGA", family: "a350", operator: "Turkish Airlines", yearBuilt: 2020 },
  { registration: "TC-LGO", family: "a350", operator: "Turkish Airlines", yearBuilt: 2023 },
  // a380
  { registration: "9M-MNA", family: "a380", operator: "Malaysia Airlines", yearBuilt: 2011 },
  { registration: "9M-MNF", family: "a380", operator: "Malaysia Airlines", yearBuilt: 2012 },
  { registration: "9V-SKB", family: "a380", operator: "Singapore Airlines", yearBuilt: 2006 },
  { registration: "9V-SKF", family: "a380", operator: "Singapore Airlines", yearBuilt: 2008 },
  { registration: "9V-SKI", family: "a380", operator: "Singapore Airlines", yearBuilt: 2009 },
  { registration: "9V-SKP", family: "a380", operator: "Singapore Airlines", yearBuilt: 2011 },
  { registration: "9V-SKY", family: "a380", operator: "Singapore Airlines", yearBuilt: 2018 },
  { registration: "A6-APA", family: "a380", operator: "Etihad Airways", yearBuilt: 2014 },
  { registration: "A6-APB", family: "a380", operator: "Etihad Airways", yearBuilt: 2014 },
  { registration: "A6-APC", family: "a380", operator: "Etihad Airways", yearBuilt: 2014 },
  { registration: "A6-EDA", family: "a380", operator: "Emirates Airline", yearBuilt: 2007 },
  { registration: "A6-EDC", family: "a380", operator: "Emirates Airline", yearBuilt: 2008 },
  { registration: "A6-EDG", family: "a380", operator: "Emirates Airline", yearBuilt: 2009 },
  { registration: "A6-EDJ", family: "a380", operator: "Emirates Airline", yearBuilt: 2006 },
  { registration: "A6-EDN", family: "a380", operator: "Emirates Airline", yearBuilt: 2010 },
  { registration: "A6-EDR", family: "a380", operator: "Emirates Airline", yearBuilt: 2011 },
  { registration: "A6-EDX", family: "a380", operator: "Emirates Airline", yearBuilt: 2012 },
  { registration: "A6-EEE", family: "a380", operator: "Emirates Airline", yearBuilt: 2012 },
  { registration: "A7-APB", family: "a380", operator: "Qatar Airways", yearBuilt: 2013 },
  { registration: "A7-APC", family: "a380", operator: "Qatar Airways", yearBuilt: 2013 },
  { registration: "A7-APE", family: "a380", operator: "Qatar Airways", yearBuilt: 2015 },
  { registration: "A7-APG", family: "a380", operator: "Qatar Airways", yearBuilt: 2016 },
  { registration: "A7-APJ", family: "a380", operator: "Qatar Airways", yearBuilt: 2017 },
  { registration: "B-6136", family: "a380", operator: "China Southern Airlines", yearBuilt: 2011 },
  { registration: "B-6137", family: "a380", operator: "China Southern Airlines", yearBuilt: 2011 },
  { registration: "D-AIMA", family: "a380", operator: "Lufthansa", yearBuilt: 2010 },
  { registration: "D-AIMB", family: "a380", operator: "Lufthansa", yearBuilt: 2010 },
  { registration: "D-AIMD", family: "a380", operator: "Lufthansa", yearBuilt: 2010 },
  { registration: "D-AIMI", family: "a380", operator: "Lufthansa", yearBuilt: 2011 },
  { registration: "D-AIMK", family: "a380", operator: "Lufthansa", yearBuilt: 2013 },
  { registration: "D-AIMM", family: "a380", operator: "Lufthansa", yearBuilt: 2014 },
  { registration: "F-HPJB", family: "a380", operator: "Air France", yearBuilt: 2009 },
  { registration: "F-HPJG", family: "a380", operator: "Air France", yearBuilt: 2011 },
  { registration: "F-HPJJ", family: "a380", operator: "Air France", yearBuilt: 2013 },
  { registration: "G-XLEA", family: "a380", operator: "British Airways", yearBuilt: 2012 },
  { registration: "G-XLEB", family: "a380", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-XLEC", family: "a380", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-XLED", family: "a380", operator: "British Airways", yearBuilt: 2013 },
  { registration: "HL7611", family: "a380", operator: "Korean Air", yearBuilt: 2010 },
  { registration: "HL7612", family: "a380", operator: "Korean Air", yearBuilt: 2011 },
  { registration: "HL7625", family: "a380", operator: "Asiana Airlines", yearBuilt: 2013 },
  { registration: "HL7626", family: "a380", operator: "Asiana Airlines", yearBuilt: 2013 },
  { registration: "HS-TUA", family: "a380", operator: "Thai Airways International", yearBuilt: 2012 },
  { registration: "HS-TUB", family: "a380", operator: "Thai Airways International", yearBuilt: 2012 },
  { registration: "HS-TUC", family: "a380", operator: "Thai Airways International", yearBuilt: 2012 },
  { registration: "JA381A", family: "a380", operator: "All Nippon Airways", yearBuilt: 2018 },
  { registration: "JA382A", family: "a380", operator: "All Nippon Airways", yearBuilt: 2018 },
  { registration: "VH-OQC", family: "a380", operator: "Qantas", yearBuilt: 2008 },
  { registration: "VH-OQD", family: "a380", operator: "Qantas", yearBuilt: 2008 },
  { registration: "VH-OQF", family: "a380", operator: "Qantas", yearBuilt: 2009 },
  { registration: "VH-OQG", family: "a380", operator: "Qantas", yearBuilt: 2009 },
  // 737
  { registration: "C-FWVJ", family: "737", operator: "WestJet", yearBuilt: 2011 },
  { registration: "C-GJWS", family: "737", operator: "WestJet", yearBuilt: 2005 },
  { registration: "C-GKWJ", family: "737", operator: "WestJet", yearBuilt: 2005 },
  { registration: "C-GWSR", family: "737", operator: "WestJet", yearBuilt: 2009 },
  { registration: "C-GWSV", family: "737", operator: "WestJet", yearBuilt: 2009 },
  { registration: "D-ABKI", family: "737", operator: "TUIfly", yearBuilt: 2009 },
  { registration: "D-AMAD", family: "737", operator: "TUIfly", yearBuilt: 2023 },
  { registration: "D-AMAH", family: "737", operator: "TUIfly", yearBuilt: 2023 },
  { registration: "D-AMAY", family: "737", operator: "TUIfly", yearBuilt: 2018 },
  { registration: "D-AMAZ", family: "737", operator: "TUIfly", yearBuilt: 2020 },
  { registration: "EI-DCJ", family: "737", operator: "Ryanair", yearBuilt: 2004 },
  { registration: "EI-DCM", family: "737", operator: "Ryanair", yearBuilt: 2004 },
  { registration: "EI-DCN", family: "737", operator: "Ryanair", yearBuilt: 2004 },
  { registration: "EI-DCO", family: "737", operator: "Ryanair", yearBuilt: 2004 },
  { registration: "EI-FRE", family: "737", operator: "Ryanair", yearBuilt: 2016 },
  { registration: "G-DRTA", family: "737", operator: "Jet2", yearBuilt: 2004 },
  { registration: "G-DRTB", family: "737", operator: "Jet2", yearBuilt: 1999 },
  { registration: "G-DRTC", family: "737", operator: "Jet2", yearBuilt: 2006 },
  { registration: "G-DRTK", family: "737", operator: "Jet2", yearBuilt: 2013 },
  { registration: "G-DRTV", family: "737", operator: "Jet2", yearBuilt: 2015 },
  { registration: "LN-NIP", family: "737", operator: "Norwegian Air Shuttle", yearBuilt: 2013 },
  { registration: "LN-NOL", family: "737", operator: "Norwegian Air Shuttle", yearBuilt: 2009 },
  { registration: "LN-NOV", family: "737", operator: "Norwegian Air Shuttle", yearBuilt: 2010 },
  { registration: "N17753", family: "737", operator: "United Airlines", yearBuilt: 2002 },
  { registration: "N200WN", family: "737", operator: "Southwest Airlines", yearBuilt: 2005 },
  { registration: "N201LV", family: "737", operator: "Southwest Airlines", yearBuilt: 2005 },
  { registration: "N371DA", family: "737", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "N372DA", family: "737", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "N3730B", family: "737", operator: "Delta Air Lines", yearBuilt: 2000 },
  { registration: "N3731T", family: "737", operator: "Delta Air Lines", yearBuilt: 2000 },
  { registration: "N3744F", family: "737", operator: "Delta Air Lines", yearBuilt: 1967 },
  { registration: "N506AS", family: "737", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N508AS", family: "737", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N512AS", family: "737", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N516AS", family: "737", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N517AS", family: "737", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N7723E", family: "737", operator: "Southwest Airlines", yearBuilt: 2006 },
  { registration: "N77537", family: "737", operator: "United Airlines", yearBuilt: 2016 },
  { registration: "N77539", family: "737", operator: "United Airlines", yearBuilt: 2017 },
  { registration: "N79541", family: "737", operator: "United Airlines", yearBuilt: 2017 },
  { registration: "N819NN", family: "737", operator: "American Airlines", yearBuilt: 2009 },
  { registration: "N820SY", family: "737", operator: "Sun Country Airlines", yearBuilt: 2014 },
  { registration: "N821SY", family: "737", operator: "Sun Country Airlines", yearBuilt: 2014 },
  { registration: "N823NN", family: "737", operator: "American Airlines", yearBuilt: 2010 },
  { registration: "N824SY", family: "737", operator: "Sun Country Airlines", yearBuilt: 2005 },
  { registration: "N827SY", family: "737", operator: "Sun Country Airlines", yearBuilt: 2006 },
  { registration: "N837SY", family: "737", operator: "Sun Country Airlines", yearBuilt: 2012 },
  { registration: "N8576Z", family: "737", operator: "Southwest Airlines", yearBuilt: 2018 },
  { registration: "N8695D", family: "737", operator: "Southwest Airlines", yearBuilt: 2016 },
  { registration: "N8696E", family: "737", operator: "Southwest Airlines", yearBuilt: 2016 },
  { registration: "N901AN", family: "737", operator: "American Airlines", yearBuilt: 1999 },
  { registration: "N902AN", family: "737", operator: "American Airlines", yearBuilt: 1999 },
  { registration: "N903AN", family: "737", operator: "American Airlines", yearBuilt: 1999 },
  { registration: "PH-BXB", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 1999 },
  { registration: "PH-BXC", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 1999 },
  { registration: "PH-BXD", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 1999 },
  { registration: "PH-BXE", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 2000 },
  { registration: "PH-BXF", family: "737", operator: "KLM Royal Dutch Airlines", yearBuilt: 2000 },
  { registration: "VH-VXA", family: "737", operator: "Qantas", yearBuilt: 2001 },
  { registration: "VH-VXB", family: "737", operator: "Qantas", yearBuilt: 2001 },
  { registration: "VH-VXC", family: "737", operator: "Qantas", yearBuilt: 2001 },
  { registration: "VH-VXP", family: "737", operator: "Qantas", yearBuilt: 2003 },
  { registration: "VH-VXT", family: "737", operator: "Qantas", yearBuilt: 2003 },
  // 737
  { registration: "G-DRTN", family: "737", operator: "Jet2" },
  { registration: "G-JZHK", family: "737", operator: "Jet2", yearBuilt: 2016 },
  { registration: "G-TAWC", family: "737", operator: "TUI Airways", yearBuilt: 2012 },
  { registration: "N579UA", family: "737", operator: "United Airlines", yearBuilt: 2003 },
  { registration: "VH-YFG", family: "737", operator: "Korean Air", yearBuilt: 2012 },
  // 757
  { registration: "G-LSAA", family: "757", operator: "Jet2", yearBuilt: 1988 },
  { registration: "G-LSAB", family: "757", operator: "Jet2", yearBuilt: 1988 },
  { registration: "G-LSAC", family: "757", operator: "Jet2", yearBuilt: 1992 },
  { registration: "G-LSAD", family: "757", operator: "Jet2", yearBuilt: 1989 },
  { registration: "G-LSAL", family: "757", operator: "Jet2", yearBuilt: 1993 },
  { registration: "G-LSAN", family: "757", operator: "Jet2", yearBuilt: 1994 },
  { registration: "N189AN", family: "757", operator: "American Airlines", yearBuilt: 2001 },
  { registration: "N405UP", family: "757", operator: "UPS", yearBuilt: 1987 },
  { registration: "N412UP", family: "757", operator: "UPS", yearBuilt: 1988 },
  { registration: "N413UP", family: "757", operator: "UPS", yearBuilt: 1988 },
  { registration: "N420UP", family: "757", operator: "UPS", yearBuilt: 1990 },
  { registration: "N427UP", family: "757", operator: "UPS", yearBuilt: 1992 },
  { registration: "N433UP", family: "757", operator: "UPS", yearBuilt: 1993 },
  { registration: "N434UP", family: "757", operator: "UPS", yearBuilt: 1993 },
  { registration: "N446UP", family: "757", operator: "UPS", yearBuilt: 1994 },
  { registration: "N452UP", family: "757", operator: "UPS", yearBuilt: 1995 },
  { registration: "N459UP", family: "757", operator: "UPS", yearBuilt: 1996 },
  { registration: "N472UP", family: "757", operator: "UPS", yearBuilt: 1998 },
  { registration: "N521UA", family: "757", operator: "United Airlines", yearBuilt: 1990 },
  { registration: "N523UA", family: "757", operator: "United Airlines", yearBuilt: 1990 },
  { registration: "N529UA", family: "757", operator: "United Airlines", yearBuilt: 1991 },
  { registration: "N532UA", family: "757", operator: "United Airlines", yearBuilt: 1991 },
  { registration: "N540UA", family: "757", operator: "United Airlines", yearBuilt: 1991 },
  { registration: "N546UA", family: "757", operator: "United Airlines", yearBuilt: 1991 },
  { registration: "N551UA", family: "757", operator: "United Airlines", yearBuilt: 1992 },
  { registration: "N556UA", family: "757", operator: "United Airlines", yearBuilt: 1992 },
  { registration: "N565UA", family: "757", operator: "United Airlines", yearBuilt: 1992 },
  { registration: "N583NW", family: "757", operator: "Delta Air Lines", yearBuilt: 2002 },
  { registration: "N585UA", family: "757", operator: "United Airlines", yearBuilt: 1993 },
  { registration: "N594NW", family: "757", operator: "Delta Air Lines", yearBuilt: 2003 },
  { registration: "N605AA", family: "757", operator: "American Airlines", yearBuilt: 1995 },
  { registration: "N608DA", family: "757", operator: "Delta Air Lines", yearBuilt: 1985 },
  { registration: "N609AA", family: "757", operator: "American Airlines", yearBuilt: 1996 },
  { registration: "N614DL", family: "757", operator: "Delta Air Lines", yearBuilt: 1985 },
  { registration: "N625DL", family: "757", operator: "Delta Air Lines", yearBuilt: 1987 },
  { registration: "N630AA", family: "757", operator: "American Airlines", yearBuilt: 1990 },
  { registration: "N633AA", family: "757", operator: "American Airlines", yearBuilt: 1990 },
  { registration: "N648AA", family: "757", operator: "American Airlines", yearBuilt: 1991 },
  { registration: "N652DL", family: "757", operator: "Delta Air Lines", yearBuilt: 1989 },
  { registration: "N653A", family: "757", operator: "American Airlines", yearBuilt: 1991 },
  { registration: "N658DL", family: "757", operator: "Delta Air Lines", yearBuilt: 1990 },
  { registration: "N6713Y", family: "757", operator: "Delta Air Lines" },
  { registration: "N672AA", family: "757", operator: "American Airlines", yearBuilt: 1992 },
  { registration: "N674DL", family: "757", operator: "Delta Air Lines", yearBuilt: 1992 },
  { registration: "N677AN", family: "757", operator: "American Airlines", yearBuilt: 1998 },
  { registration: "N695AN", family: "757", operator: "American Airlines", yearBuilt: 1994 },
  { registration: "N709TW", family: "757", operator: "Delta Air Lines", yearBuilt: 1997 },
  { registration: "N712TW", family: "757", operator: "Delta Air Lines", yearBuilt: 1997 },
  { registration: "N752NA", family: "757", operator: "American Airlines", yearBuilt: 1999 },
  { registration: "N790FD", family: "757", operator: "FedEx Express", yearBuilt: 1993 },
  { registration: "N903FD", family: "757", operator: "FedEx Express", yearBuilt: 1993 },
  { registration: "N909FD", family: "757", operator: "FedEx Express", yearBuilt: 1993 },
  { registration: "N910FD", family: "757", operator: "FedEx Express", yearBuilt: 1991 },
  { registration: "N915FD", family: "757", operator: "FedEx Express", yearBuilt: 1988 },
  { registration: "N919FD", family: "757", operator: "FedEx Express", yearBuilt: 1990 },
  { registration: "N923FD", family: "757", operator: "FedEx Express", yearBuilt: 1992 },
  { registration: "N927FD", family: "757", operator: "FedEx Express", yearBuilt: 1994 },
  { registration: "N959FD", family: "757", operator: "FedEx Express", yearBuilt: 1991 },
  { registration: "N962FD", family: "757", operator: "FedEx Express", yearBuilt: 1988 },
  { registration: "N967FD", family: "757", operator: "FedEx Express", yearBuilt: 1994 },
  { registration: "N968FD", family: "757", operator: "FedEx Express", yearBuilt: 1995 },
  { registration: "TF-FIG", family: "757", operator: "Icelandair", yearBuilt: 1989 },
  { registration: "TF-FII", family: "757", operator: "Icelandair", yearBuilt: 1990 },
  { registration: "TF-FIJ", family: "757", operator: "Icelandair", yearBuilt: 1991 },
  { registration: "TF-FIN", family: "757", operator: "Icelandair", yearBuilt: 1997 },
  { registration: "TF-FIR", family: "757", operator: "Icelandair", yearBuilt: 1994 },
  { registration: "TF-FIS", family: "757", operator: "Icelandair", yearBuilt: 1994 },
  { registration: "TF-ISK", family: "757", operator: "Icelandair", yearBuilt: 1991 },
  { registration: "TF-ISR", family: "757", operator: "Icelandair", yearBuilt: 1999 },
  { registration: "TF-ISS", family: "757", operator: "Icelandair", yearBuilt: 1996 },
  { registration: "TF-ISY", family: "757", operator: "Icelandair", yearBuilt: 1991 },
  { registration: "TF-LLX", family: "757", operator: "Icelandair", yearBuilt: 2000 },
  // 767
  { registration: "N534LA", family: "767", operator: "LATAM Airlines", yearBuilt: 2001 },
  { registration: "VH-OGD", family: "767", operator: "Cathay Pacific Airways", yearBuilt: 1988 },
  // 777
  { registration: "TC-LJO", family: "777", operator: "Turkish Airlines", yearBuilt: 2018 },
  // a320
  { registration: "A6-EIB", family: "a320", operator: "Etihad Airways", yearBuilt: 2003 },
  { registration: "A6-EII", family: "a320", operator: "Etihad Airways", yearBuilt: 2008 },
  { registration: "A6-EIK", family: "a320", operator: "Etihad Airways", yearBuilt: 2008 },
  { registration: "A6-EIL", family: "a320", operator: "Etihad Airways", yearBuilt: 2009 },
  { registration: "A6-EIP", family: "a320", operator: "Etihad Airways", yearBuilt: 2012 },
  { registration: "A6-EIX", family: "a320", operator: "Etihad Airways", yearBuilt: 2014 },
  { registration: "A6-EIY", family: "a320", operator: "Etihad Airways" },
  { registration: "A7-AAG", family: "a320", operator: "Qatar Amiri Flight", yearBuilt: 1999 },
  { registration: "A7-AHB", family: "a320", operator: "Qatar Airways", yearBuilt: 2009 },
  { registration: "A7-AHP", family: "a320", operator: "Qatar Airways", yearBuilt: 2011 },
  { registration: "A7-AHW", family: "a320", operator: "Qatar Airways", yearBuilt: 2012 },
  { registration: "A7-AHX", family: "a320", operator: "Qatar Airways", yearBuilt: 2012 },
  { registration: "A7-AHY", family: "a320", operator: "Qatar Airways", yearBuilt: 2012 },
  { registration: "A7-LAG", family: "a320", operator: "Qatar Airways", yearBuilt: 2015 },
  { registration: "B-2351", family: "a320", operator: "China Southern Airlines", yearBuilt: 1997 },
  { registration: "B-2376", family: "a320", operator: "Air China", yearBuilt: 1998 },
  { registration: "B-2377", family: "a320", operator: "Air China", yearBuilt: 1998 },
  { registration: "B-305J", family: "a320", operator: "Air China" },
  { registration: "B-6276", family: "a320", operator: "China Southern Airlines" },
  { registration: "B-6292", family: "a320", operator: "China Southern Airlines", yearBuilt: 2006 },
  { registration: "B-6677", family: "a320", operator: "Air China", yearBuilt: 2010 },
  { registration: "B-6679", family: "a320", operator: "China Southern Airlines", yearBuilt: 2010 },
  { registration: "B-6911", family: "a320", operator: "China Southern Airlines", yearBuilt: 2012 },
  { registration: "B-6918", family: "a320", operator: "Air China" },
  { registration: "B-6976", family: "a320", operator: "China Southern Airlines" },
  { registration: "B-9925", family: "a320", operator: "Air China", yearBuilt: 2013 },
  { registration: "C-FGYL", family: "a320", operator: "Top Aces Inc", yearBuilt: 1991 },
  { registration: "C-FKCO", family: "a320", operator: "Air Canada", yearBuilt: 1991 },
  { registration: "C-FPWE", family: "a320", operator: "Air Canada", yearBuilt: 1991 },
  { registration: "C-FTJQ", family: "a320", operator: "Air Canada", yearBuilt: 1991 },
  { registration: "C-GQCA", family: "a320", operator: "Air Canada", yearBuilt: 1991 },
  { registration: "CC-BFO", family: "a320", operator: "LATAM Airlines" },
  { registration: "CS-TNK", family: "a320", operator: "TAP Air Portugal", yearBuilt: 2000 },
  { registration: "CS-TNU", family: "a320", operator: "TAP Air Portugal" },
  { registration: "CS-TVB", family: "a320", operator: "TAP Air Portugal", yearBuilt: 2019 },
  { registration: "CS-TVH", family: "a320", operator: "TAP Air Portugal", yearBuilt: 2020 },
  { registration: "CS-TVK", family: "a320", operator: "TAP Air Portugal", yearBuilt: 2021 },
  { registration: "D-AIPK", family: "a320", operator: "Lufthansa", yearBuilt: 1989 },
  { registration: "D-AIQD", family: "a320", operator: "Lufthansa", yearBuilt: 1991 },
  { registration: "D-AIQF", family: "a320", operator: "Lufthansa", yearBuilt: 1991 },
  { registration: "D-AIUM", family: "a320", operator: "Lufthansa", yearBuilt: 2015 },
  { registration: "D-AIUO", family: "a320", operator: "Lufthansa", yearBuilt: 2015 },
  { registration: "D-AIWA", family: "a320", operator: "Lufthansa", yearBuilt: 2017 },
  { registration: "D-AIWH", family: "a320", operator: "Lufthansa", yearBuilt: 2019 },
  { registration: "EC-FDA", family: "a320", operator: "Iberia", yearBuilt: 1991 },
  { registration: "EC-HUL", family: "a320", operator: "Iberia", yearBuilt: 2000 },
  { registration: "EC-ILR", family: "a320", operator: "Iberia", yearBuilt: 2002 },
  { registration: "EC-KAX", family: "a320", operator: "Vueling", yearBuilt: 2007 },
  { registration: "EC-KOH", family: "a320", operator: "Iberia", yearBuilt: 2004 },
  { registration: "EC-LVB", family: "a320", operator: "Vueling", yearBuilt: 2000 },
  { registration: "EC-LVQ", family: "a320", operator: "Iberia", yearBuilt: 2013 },
  { registration: "EC-LVS", family: "a320", operator: "Vueling", yearBuilt: 2013 },
  { registration: "EC-LXQ", family: "a320", operator: "Iberia", yearBuilt: 2013 },
  { registration: "EC-MAO", family: "a320", operator: "Vueling", yearBuilt: 2014 },
  { registration: "EC-MBS", family: "a320", operator: "Vueling", yearBuilt: 2014 },
  { registration: "EC-MUF", family: "a320", operator: "Iberia", yearBuilt: 2007 },
  { registration: "EC-NTP", family: "a320", operator: "Iberia", yearBuilt: 2022 },
  { registration: "EC-ODM", family: "a320", operator: "Vueling", yearBuilt: 2014 },
  { registration: "EI-DEB", family: "a320", operator: "Aer Lingus", yearBuilt: 2004 },
  { registration: "EI-DEC", family: "a320", operator: "Aer Lingus", yearBuilt: 2004 },
  { registration: "EI-DEH", family: "a320", operator: "Aer Lingus", yearBuilt: 2004 },
  { registration: "EI-DEN", family: "a320", operator: "Aer Lingus", yearBuilt: 2005 },
  { registration: "EI-DER", family: "a320", operator: "Aer Lingus", yearBuilt: 2005 },
  { registration: "EI-DTM", family: "a320", operator: "ITA Airways", yearBuilt: 2010 },
  { registration: "EI-DVE", family: "a320", operator: "Aer Lingus", yearBuilt: 2007 },
  { registration: "EI-EDP", family: "a320", operator: "Aer Lingus", yearBuilt: 2009 },
  { registration: "EI-EZW", family: "a320", operator: "Aer Lingus", yearBuilt: 2003 },
  { registration: "EI-SIC", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2017 },
  { registration: "EI-SIK", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2022 },
  { registration: "EI-SIY", family: "a320", operator: "Scandinavian Airlines" },
  { registration: "F-GFKY", family: "a320", operator: "Air France", yearBuilt: 1991 },
  { registration: "F-GJVC", family: "a320", operator: "Air France", yearBuilt: 1991 },
  { registration: "F-GJVG", family: "a320", operator: "Air France", yearBuilt: 1991 },
  { registration: "F-GKXJ", family: "a320", operator: "Air France", yearBuilt: 2002 },
  { registration: "F-HBNE", family: "a320", operator: "Air France", yearBuilt: 2011 },
  { registration: "F-HEPI", family: "a320", operator: "Air France", yearBuilt: 2017 },
  { registration: "G-EJCA", family: "a320", operator: "easyJet", yearBuilt: 2013 },
  { registration: "G-EUUE", family: "a320", operator: "British Airways", yearBuilt: 2002 },
  { registration: "G-EUYA", family: "a320", operator: "British Airways", yearBuilt: 2008 },
  { registration: "G-EUYP", family: "a320", operator: "British Airways", yearBuilt: 2013 },
  { registration: "G-EUYT", family: "a320", operator: "British Airways", yearBuilt: 2014 },
  { registration: "G-EZPV", family: "a320", operator: "easyJet", yearBuilt: 2017 },
  { registration: "G-EZTG", family: "a320", operator: "easyJet", yearBuilt: 2009 },
  { registration: "G-GATP", family: "a320", operator: "British Airways", yearBuilt: 2002 },
  { registration: "G-MIDO", family: "a320", operator: "British Airways", yearBuilt: 2002 },
  { registration: "G-UZHZ", family: "a320", operator: "easyJet", yearBuilt: 2019 },
  { registration: "HA-LJB", family: "a320", operator: "Wizz Air", yearBuilt: 2020 },
  { registration: "HA-LYV", family: "a320", operator: "Wizz Air", yearBuilt: 2008 },
  { registration: "HB-IJD", family: "a320", operator: "Swiss International Air Lines", yearBuilt: 1995 },
  { registration: "HB-IJE", family: "a320", operator: "Swiss International Air Lines", yearBuilt: 1995 },
  { registration: "HB-IJO", family: "a320", operator: "Swiss International Air Lines" },
  { registration: "HB-IJP", family: "a320", operator: "Swiss International Air Lines", yearBuilt: 1997 },
  { registration: "HB-IJS", family: "a320", operator: "Swiss International Air Lines", yearBuilt: 1998 },
  { registration: "HB-IJW", family: "a320", operator: "Edelweiss Air", yearBuilt: 2003 },
  { registration: "N314US", family: "a320", operator: "Delta Air Lines", yearBuilt: 1991 },
  { registration: "N333NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 1992 },
  { registration: "N336NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 1992 },
  { registration: "N355NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "N356NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 1998 },
  { registration: "N377NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 2003 },
  { registration: "N378NW", family: "a320", operator: "Delta Air Lines", yearBuilt: 2003 },
  { registration: "N440UA", family: "a320", operator: "United Airlines", yearBuilt: 1997 },
  { registration: "N448UA", family: "a320", operator: "United Airlines", yearBuilt: 1998 },
  { registration: "N474UA", family: "a320", operator: "United Airlines" },
  { registration: "N534JB", family: "a320", operator: "JetBlue", yearBuilt: 2002 },
  { registration: "N536JB", family: "a320", operator: "JetBlue", yearBuilt: 2002 },
  { registration: "N549VL", family: "a320", operator: "Volaris", yearBuilt: 2023 },
  { registration: "N623VA", family: "a320", operator: "Alaska Airlines", yearBuilt: 2006 },
  { registration: "N636VA", family: "a320", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N641VA", family: "a320", operator: "Alaska Airlines", yearBuilt: 2008 },
  { registration: "N657AW", family: "a320", operator: "American Airlines", yearBuilt: 1999 },
  { registration: "N661JB", family: "a320", operator: "JetBlue", yearBuilt: 2007 },
  { registration: "N673AW", family: "a320", operator: "American Airlines", yearBuilt: 2004 },
  { registration: "N703JB", family: "a320", operator: "JetBlue", yearBuilt: 2008 },
  { registration: "N729JB", family: "a320", operator: "JetBlue", yearBuilt: 2008 },
  { registration: "N763AV", family: "a320", operator: "Avianca" },
  { registration: "N768JB", family: "a320", operator: "JetBlue", yearBuilt: 2008 },
  { registration: "N809JB", family: "a320", operator: "JetBlue", yearBuilt: 2012 },
  { registration: "N844VA", family: "a320", operator: "Alaska Airlines" },
  { registration: "N846VA", family: "a320", operator: "Alaska Airlines", yearBuilt: 2011 },
  { registration: "N966AV", family: "a320", operator: "Avianca", yearBuilt: 2022 },
  { registration: "OE-ICP", family: "a320", operator: "easyJet", yearBuilt: 2015 },
  { registration: "OE-IVL", family: "a320", operator: "easyJet", yearBuilt: 2014 },
  { registration: "OE-LBI", family: "a320", operator: "Austrian Airlines", yearBuilt: 2003 },
  { registration: "OE-LBL", family: "a320", operator: "Austrian Airlines", yearBuilt: 2003 },
  { registration: "OE-LBW", family: "a320", operator: "Austrian Airlines", yearBuilt: 2001 },
  { registration: "OE-LBZ", family: "a320", operator: "Austrian Airlines", yearBuilt: 2012 },
  { registration: "OE-LXA", family: "a320", operator: "Austrian Airlines", yearBuilt: 2007 },
  { registration: "OE-LXC", family: "a320", operator: "Austrian Airlines", yearBuilt: 2008 },
  { registration: "OE-LZA", family: "a320", operator: "Austrian Airlines" },
  { registration: "OE-LZB", family: "a320", operator: "Austrian Airlines", yearBuilt: 2007 },
  { registration: "OH-LXB", family: "a320", operator: "Finnair", yearBuilt: 2001 },
  { registration: "OH-LXF", family: "a320", operator: "Finnair", yearBuilt: 2002 },
  { registration: "OH-LXG", family: "a320", operator: "Finnair", yearBuilt: 2002 },
  { registration: "OH-LXL", family: "a320", operator: "Finnair", yearBuilt: 2003 },
  { registration: "OH-LXM", family: "a320", operator: "Finnair", yearBuilt: 2003 },
  { registration: "OY-KAO", family: "a320", operator: "Vueling", yearBuilt: 2006 },
  { registration: "OY-KAT", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2007 },
  { registration: "SE-ROS", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2019 },
  { registration: "SE-ROZ", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2020 },
  { registration: "SE-RZY", family: "a320", operator: "Scandinavian Airlines", yearBuilt: 2024 },
  // a330
  { registration: "9M-MKJ", family: "a330", operator: "Malaysia Airlines", yearBuilt: 1995 },
  { registration: "9M-MKV", family: "a330", operator: "Malaysia Airlines", yearBuilt: 1999 },
  { registration: "9M-MTL", family: "a330", operator: "Malaysia Airlines", yearBuilt: 2013 },
  { registration: "9M-MTX", family: "a330", operator: "Malaysia Airlines", yearBuilt: 2008 },
  { registration: "A6-AFA", family: "a330", operator: "Etihad Airways", yearBuilt: 2009 },
  { registration: "A6-AFD", family: "a330", operator: "Etihad Airways", yearBuilt: 2011 },
  { registration: "A7-ACJ", family: "a330", operator: "Qatar Airways", yearBuilt: 2006 },
  { registration: "A7-AEC", family: "a330", operator: "Qatar Airways", yearBuilt: 2005 },
  { registration: "A7-AEE", family: "a330", operator: "Qatar Airways", yearBuilt: 2005 },
  { registration: "A7-AEJ", family: "a330", operator: "Qatar Airways", yearBuilt: 2007 },
  { registration: "A7-AFV", family: "a330", operator: "Qatar Airways", yearBuilt: 2012 },
  { registration: "B-18305", family: "a330", operator: "China Airlines", yearBuilt: 2005 },
  { registration: "B-18310", family: "a330", operator: "China Airlines", yearBuilt: 2005 },
  { registration: "B-18315", family: "a330", operator: "China Airlines", yearBuilt: 2007 },
  { registration: "C-GEGC", family: "a330", operator: "Air Canada", yearBuilt: 2009 },
  { registration: "C-GFUR", family: "a330", operator: "Air Canada", yearBuilt: 2000 },
  { registration: "C-GHKW", family: "a330", operator: "Air Canada", yearBuilt: 2001 },
  { registration: "C-GHKX", family: "a330", operator: "Air Canada", yearBuilt: 2001 },
  { registration: "C-GHLM", family: "a330", operator: "Air Canada", yearBuilt: 2001 },
  { registration: "CS-TOE", family: "a330", operator: "TAP Air Portugal", yearBuilt: 1999 },
  { registration: "CS-TOG", family: "a330", operator: "TAP Air Portugal", yearBuilt: 1999 },
  { registration: "CS-TOO", family: "a330", operator: "TAP Air Portugal", yearBuilt: 2008 },
  { registration: "CS-TOS", family: "a330", operator: "TAP Air Portugal", yearBuilt: 2000 },
  { registration: "D-AIKK", family: "a330", operator: "Discover Airlines", yearBuilt: 2008 },
  { registration: "D-AIKL", family: "a330", operator: "Lufthansa", yearBuilt: 2008 },
  { registration: "D-AIKN", family: "a330", operator: "Lufthansa", yearBuilt: 2008 },
  { registration: "D-AIKP", family: "a330", operator: "Lufthansa" },
  { registration: "EC-LZX", family: "a330", operator: "Iberia", yearBuilt: 2014 },
  { registration: "EC-MJA", family: "a330", operator: "Iberia", yearBuilt: 2016 },
  { registration: "EC-MLP", family: "a330", operator: "Iberia", yearBuilt: 2016 },
  { registration: "EC-MMG", family: "a330", operator: "Iberia", yearBuilt: 2016 },
  { registration: "EC-NEN", family: "a330", operator: "Level", yearBuilt: 2019 },
  { registration: "EI-DUB", family: "a330", operator: "Aer Lingus", yearBuilt: 1994 },
  { registration: "EI-ELA", family: "a330", operator: "Aer Lingus", yearBuilt: 2010 },
  { registration: "EI-GAJ", family: "a330", operator: "Aer Lingus", yearBuilt: 2017 },
  { registration: "F-GZCD", family: "a330", operator: "Air France", yearBuilt: 2002 },
  { registration: "F-GZCG", family: "a330", operator: "Air France", yearBuilt: 2002 },
  { registration: "F-GZCJ", family: "a330", operator: "Air France", yearBuilt: 2002 },
  { registration: "F-GZCL", family: "a330", operator: "Air France", yearBuilt: 2003 },
  { registration: "F-GZCO", family: "a330", operator: "Air France", yearBuilt: 2006 },
  { registration: "G-EILA", family: "a330", operator: "Aer Lingus", yearBuilt: 2010 },
  { registration: "G-VKSS", family: "a330", operator: "Virgin Atlantic", yearBuilt: 2010 },
  { registration: "G-VLUV", family: "a330", operator: "Virgin Atlantic", yearBuilt: 2010 },
  { registration: "G-VSRB", family: "a330", operator: "Virgin Atlantic" },
  { registration: "G-VWAG", family: "a330", operator: "Virgin Atlantic", yearBuilt: 2012 },
  { registration: "HB-IQH", family: "a330", operator: "Swiss International Air Lines", yearBuilt: 1999 },
  { registration: "HB-IQI", family: "a330", operator: "Swiss International Air Lines", yearBuilt: 1999 },
  { registration: "HB-IQQ", family: "a330", operator: "Swiss International Air Lines", yearBuilt: 2000 },
  { registration: "HB-JHL", family: "a330", operator: "Swiss International Air Lines", yearBuilt: 2011 },
  { registration: "HL7524", family: "a330", operator: "Korean Air" },
  { registration: "HL7586", family: "a330", operator: "Korean Air", yearBuilt: 2000 },
  { registration: "HL7747", family: "a330", operator: "Asiana Airlines" },
  { registration: "HL7792", family: "a330", operator: "Asiana Airlines", yearBuilt: 2009 },
  { registration: "HL7793", family: "a330", operator: "Asiana Airlines", yearBuilt: 2009 },
  { registration: "HL8027", family: "a330", operator: "Korean Air", yearBuilt: 2015 },
  { registration: "HL8211", family: "a330", operator: "T'way Air", yearBuilt: 2010 },
  { registration: "HL8259", family: "a330", operator: "Asiana Airlines", yearBuilt: 2012 },
  { registration: "HL8282", family: "a330", operator: "Asiana Airlines", yearBuilt: 2013 },
  { registration: "HS-TBC", family: "a330", operator: "Thai Airways International", yearBuilt: 2012 },
  { registration: "HS-TEP", family: "a330", operator: "Thai Airways International", yearBuilt: 2009 },
  { registration: "LN-RKS", family: "a330", operator: "Scandinavian Airlines", yearBuilt: 2015 },
  { registration: "LN-RKT", family: "a330", operator: "Scandinavian Airlines", yearBuilt: 2016 },
  { registration: "LN-RKU", family: "a330", operator: "Scandinavian Airlines", yearBuilt: 2016 },
  { registration: "N407DX", family: "a330", operator: "Delta Air Lines", yearBuilt: 2020 },
  { registration: "N829NW", family: "a330", operator: "Delta Air Lines", yearBuilt: 2016 },
  { registration: "N859NW", family: "a330", operator: "Delta Air Lines", yearBuilt: 2006 },
  { registration: "N860NW", family: "a330", operator: "Delta Air Lines", yearBuilt: 2006 },
  { registration: "OH-LTN", family: "a330", operator: "Finnair", yearBuilt: 2009 },
  { registration: "OH-LTO", family: "a330", operator: "Finnair", yearBuilt: 2009 },
  { registration: "OH-LTP", family: "a330", operator: "Finnair", yearBuilt: 2009 },
  { registration: "OH-LTU", family: "a330", operator: "Finnair", yearBuilt: 2010 },
  { registration: "OY-VKF", family: "a330", operator: "Sunclass Airlines", yearBuilt: 1999 },
  { registration: "PH-AKE", family: "a330", operator: "KLM Royal Dutch Airlines", yearBuilt: 2012 },
  { registration: "PH-AOC", family: "a330", operator: "KLM Royal Dutch Airlines", yearBuilt: 2005 },
  { registration: "PH-AOM", family: "a330", operator: "KLM Royal Dutch Airlines", yearBuilt: 2010 },
  { registration: "PH-AON", family: "a330", operator: "KLM Royal Dutch Airlines", yearBuilt: 2008 },
  { registration: "SE-REH", family: "a330", operator: "Scandinavian Airlines", yearBuilt: 2019 },
  { registration: "TC-JND", family: "a330", operator: "Turkish Airlines", yearBuilt: 2006 },
  { registration: "TC-LNG", family: "a330", operator: "Turkish Airlines", yearBuilt: 2016 },
  { registration: "TC-LOH", family: "a330", operator: "Turkish Airlines", yearBuilt: 2011 },
  { registration: "VH-EBI", family: "a330", operator: "Qantas", yearBuilt: 2008 },
  { registration: "VH-EBM", family: "a330", operator: "Qantas", yearBuilt: 2009 },
  { registration: "VH-EBS", family: "a330", operator: "Qantas", yearBuilt: 2011 },
  { registration: "VH-QPD", family: "a330", operator: "Qantas", yearBuilt: 2004 },
  // a380
  { registration: "D-AIMC", family: "a380", operator: "Lufthansa", yearBuilt: 2010 },
  // e190
  { registration: "C-FHNY", family: "e190", operator: "Air Canada", yearBuilt: 2007 },
  { registration: "C-FLWE", family: "e190", operator: "Air Canada", yearBuilt: 2007 },
  { registration: "C-FMYV", family: "e190", operator: "Air Canada", yearBuilt: 2007 },
  { registration: "CS-TPP", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2011 },
  { registration: "CS-TPQ", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2011 },
  { registration: "CS-TPS", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2011 },
  { registration: "CS-TPY", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2009 },
  { registration: "CS-TPZ", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2009 },
  { registration: "CS-TTY", family: "e190", operator: "TAP Air Portugal", yearBuilt: 2013 },
  { registration: "F-HBLE", family: "e190", operator: "Air France", yearBuilt: 2007 },
  { registration: "F-HBLG", family: "e190", operator: "Air France", yearBuilt: 2009 },
  { registration: "F-HBLH", family: "e190", operator: "Air France", yearBuilt: 2009 },
  { registration: "F-HBLI", family: "e190", operator: "Air France", yearBuilt: 2009 },
  { registration: "F-HBLK", family: "e190", operator: "Air France", yearBuilt: 2018 },
  { registration: "F-HBLM", family: "e190", operator: "Air France", yearBuilt: 2019 },
  { registration: "F-HBLN", family: "e190", operator: "Air France", yearBuilt: 2019 },
  { registration: "G-LCAC", family: "e190", operator: "British Airways", yearBuilt: 2012 },
  { registration: "G-LCYK", family: "e190", operator: "British Airways", yearBuilt: 2010 },
  { registration: "G-LCYN", family: "e190", operator: "British Airways", yearBuilt: 2010 },
  { registration: "G-LCYT", family: "e190", operator: "British Airways", yearBuilt: 2014 },
  { registration: "G-LCYX", family: "e190", operator: "British Airways", yearBuilt: 2008 },
  { registration: "G-LCYZ", family: "e190", operator: "British Airways", yearBuilt: 2011 },
  { registration: "N231JB", family: "e190", operator: "JetBlue" },
  { registration: "N266JB", family: "e190", operator: "JetBlue", yearBuilt: 2007 },
  { registration: "N267JB", family: "e190", operator: "JetBlue", yearBuilt: 2007 },
  { registration: "N307JB", family: "e190", operator: "JetBlue", yearBuilt: 2009 },
  { registration: "N317JB", family: "e190", operator: "JetBlue", yearBuilt: 2010 },
  { registration: "N323JB", family: "e190", operator: "JetBlue" },
  { registration: "N355JB", family: "e190", operator: "JetBlue", yearBuilt: 2013 },
  { registration: "OH-LKE", family: "e190", operator: "Finnair", yearBuilt: 2007 },
  { registration: "OH-LKF", family: "e190", operator: "Finnair", yearBuilt: 2007 },
  { registration: "OH-LKG", family: "e190", operator: "Finnair", yearBuilt: 2007 },
  { registration: "OH-LKI", family: "e190", operator: "Finnair", yearBuilt: 2007 },
  { registration: "OH-LKK", family: "e190", operator: "Finnair", yearBuilt: 2007 },
  { registration: "OH-LKN", family: "e190", operator: "Finnair", yearBuilt: 2009 },
  { registration: "OH-LKO", family: "e190", operator: "Finnair", yearBuilt: 2009 },
  { registration: "PH-EXY", family: "e190", operator: "KLM Royal Dutch Airlines", yearBuilt: 2018 },
  { registration: "PH-EZN", family: "e190", operator: "KLM Royal Dutch Airlines", yearBuilt: 2010 },
  { registration: "PH-EZO", family: "e190", operator: "KLM Royal Dutch Airlines", yearBuilt: 2010 },
  { registration: "PH-EZR", family: "e190", operator: "KLM Royal Dutch Airlines", yearBuilt: 2010 },
  { registration: "PH-EZW", family: "e190", operator: "KLM Royal Dutch Airlines", yearBuilt: 2012 },
  { registration: "SP-LNA", family: "e190", operator: "LOT Polish Airlines", yearBuilt: 2011 },
  { registration: "SP-LNB", family: "e190", operator: "LOT Polish Airlines", yearBuilt: 2011 },
  { registration: "SP-LNF", family: "e190", operator: "LOT Polish Airlines", yearBuilt: 2013 },
  { registration: "SP-LNN", family: "e190", operator: "LOT Polish Airlines", yearBuilt: 2011 },
  { registration: "SP-LNO", family: "e190", operator: "LOT Polish Airlines" },
  { registration: "SP-LNP", family: "e190", operator: "LOT Polish Airlines", yearBuilt: 2007 },
  { registration: "XA-AAC", family: "e190", operator: "AeroMexico", yearBuilt: 2007 },
  { registration: "XA-CAC", family: "e190", operator: "AeroMexico", yearBuilt: 2007 },
  { registration: "XA-GAH", family: "e190", operator: "AeroMexico", yearBuilt: 2008 },
  { registration: "XA-GAI", family: "e190", operator: "AeroMexico", yearBuilt: 2014 },
  { registration: "XA-JAC", family: "e190", operator: "AeroMexico", yearBuilt: 2009 },
  // crj
  { registration: "C-FDJA", family: "crj", operator: "Air Canada", yearBuilt: 2004 },
  { registration: "C-FVKM", family: "crj", operator: "Air Canada", yearBuilt: 1995 },
  { registration: "C-FWJT", family: "crj", operator: "Air Canada", yearBuilt: 1995 },
  { registration: "C-GDJZ", family: "crj", operator: "Air Canada", yearBuilt: 2005 },
  { registration: "C-GKEU", family: "crj", operator: "Air Canada", yearBuilt: 2000 },
  { registration: "C-GOJA", family: "crj", operator: "Air Canada", yearBuilt: 2005 },
  { registration: "D-ACJE", family: "crj", operator: "Lufthansa", yearBuilt: 1996 },
  { registration: "D-ACKI", family: "crj", operator: "Lufthansa", yearBuilt: 2006 },
  { registration: "D-ACNO", family: "crj", operator: "Lufthansa" },
  { registration: "D-ACNP", family: "crj", operator: "Lufthansa", yearBuilt: 2010 },
  { registration: "D-ACNV", family: "crj", operator: "Lufthansa", yearBuilt: 2011 },
  { registration: "D-ACPQ", family: "crj", operator: "Lufthansa", yearBuilt: 2003 },
  { registration: "EC-HHI", family: "crj", operator: "Iberia" },
  { registration: "EC-JCL", family: "crj", operator: "Iberia", yearBuilt: 2004 },
  { registration: "EC-JEN", family: "crj", operator: "Iberia", yearBuilt: 2005 },
  { registration: "EC-LOX", family: "crj", operator: "Iberia", yearBuilt: 2011 },
  { registration: "EC-MNQ", family: "crj", operator: "Iberia", yearBuilt: 2016 },
  { registration: "EC-MQQ", family: "crj", operator: "Iberia", yearBuilt: 2017 },
  { registration: "EI-FPC", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2016 },
  { registration: "EI-FPD", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2016 },
  { registration: "EI-FPW", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2018 },
  { registration: "EI-GEA", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2009 },
  { registration: "F-GRJQ", family: "crj", operator: "Air France", yearBuilt: 1999 },
  { registration: "F-GRJT", family: "crj", operator: "Air France", yearBuilt: 2000 },
  { registration: "F-GRZI", family: "crj", operator: "Air France" },
  { registration: "F-HMLI", family: "crj", operator: "Air France", yearBuilt: 2011 },
  { registration: "F-HMLJ", family: "crj", operator: "Air France", yearBuilt: 2011 },
  { registration: "F-HMLO", family: "crj", operator: "Air France", yearBuilt: 2015 },
  { registration: "N298PQ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2013 },
  { registration: "N303PQ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2014 },
  { registration: "N310PQ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2014 },
  { registration: "N348PQ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2015 },
  { registration: "N732SK", family: "crj", operator: "American Airlines", yearBuilt: 2005 },
  { registration: "N752SK", family: "crj", operator: "American Airlines", yearBuilt: 2005 },
  { registration: "N780SK", family: "crj", operator: "United Airlines", yearBuilt: 2009 },
  { registration: "N804SK", family: "crj", operator: "Delta Air Lines", yearBuilt: 2006 },
  { registration: "N827SK", family: "crj", operator: "Delta Air Lines", yearBuilt: 2018 },
  { registration: "N830SK", family: "crj", operator: "Delta Air Lines", yearBuilt: 2018 },
  { registration: "N910XJ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2007 },
  { registration: "N928XJ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2008 },
  { registration: "N933XJ", family: "crj", operator: "Delta Air Lines", yearBuilt: 2008 },
  { registration: "N952SW", family: "crj", operator: "United Airlines", yearBuilt: 2003 },
  { registration: "OY-KFE", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2009 },
  { registration: "OY-KFI", family: "crj", operator: "Scandinavian Airlines", yearBuilt: 2009 },
];

/**
 * Find similar seed fiches for internal linking: same operator first,
 * then same aircraft family. Never includes the current registration.
 */
export function findSimilar(
  registration: string,
  type: string | undefined,
  operator: string | undefined,
  limit = 6,
): SeedMeta[] {
  const family = familyOf(type);
  const scored = SEED_META.filter((s) => s.registration !== registration).map(
    (s) => {
      let score = 0;
      if (operator && s.operator === operator) score += 2;
      if (family && s.family === family) score += 1;
      return { seed: s, score };
    },
  );
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.seed);
}
